#!/bin/sh
#
# /etc/rc.d/exim: start/stop exim daemon
#

SSD=/sbin/start-stop-daemon
PROG=/usr/sbin/exim
PID=/var/run/exim.pid
OPTS="-bd -q15m"

CRT=/etc/ssl/certs/exim.crt
KEY=/etc/ssl/keys/exim.key

case $1 in
start)
	if [ ! -s $CRT -o ! -s $KEY ]; then 
		/usr/bin/mksslcert $KEY $CRT
		chown mail $CRT $KEY
	fi
	$SSD --start --pidfile $PID --exec $PROG -- $OPTS
	;;
stop)
	$SSD --stop --remove-pidfile --retry 10 --pidfile $PID
	;;
restart)
	$0 stop
	$0 start
	;;
reload)
	$SSD --stop --signal HUP --pidfile $PID
	;;
status)
	$SSD --status --pidfile $PID
	case $? in
	0) echo "$PROG is running with pid $(cat $PID)" ;;
	1) echo "$PROG is not running but the pid file $PID exists" ;;
	3) echo "$PROG is not running" ;;
	4) echo "Unable to determine the program status" ;;
	esac
	;;
*)
	echo "usage: $0 [start|stop|restart|reload|status]"
	;;
esac

# End of file
