set Master $AUDIO_LEVEL% unmute
set 'Master Mono' $AUDIO_LEVEL% unmute
set Front $AUDIO_LEVEL% unmute
set PCM $AUDIO_LEVEL% unmute
set Line $AUDIO_LEVEL% unmute
set Synth $AUDIO_LEVEL% unmute
set CD $AUDIO_LEVEL% unmute
set Mic $MIC_LEVEL% unmute
set Capture $MIC_LEVEL% unmute
set Capture,1 $MIC_LEVEL% unmute
set Aux $AUDIO_LEVEL% unmute
set PCM,1 $AUDIO_LEVEL% unmute
set Wave $AUDIO_LEVEL% unmute
set Music $AUDIO_LEVEL% unmute
set AC97 $AUDIO_LEVEL% unmute
set 'Master Digital' $AUDIO_LEVEL% unmute
set DAC $AUDIO_LEVEL% unmute
set DAC,0 $AUDIO_LEVEL% unmute
set DAC,1 $AUDIO_LEVEL% unmute
set Headphone $AUDIO_LEVEL% unmute
set Playback $AUDIO_LEVEL% unmute
set Vol $AUDIO_LEVEL% unmute
set PCM,2 $AUDIO_LEVEL% unmute
set Speaker $AUDIO_LEVEL% unmute
set Igain $AUDIO_LEVEL% unmute
set Line,1 $AUDIO_LEVEL% unmute
set Phin $AUDIO_LEVEL% unmute
set Phout $AUDIO_LEVEL% unmute
set Video $AUDIO_LEVEL% unmute
set Phone $AUDIO_LEVEL% unmute
