# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1318423451);
user_pref("app.update.lastUpdateTime.background-update-timer", 1318423448);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1318423448);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1318423451);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1318423453);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 8192);
user_pref("browser.cache.offline.capacity", 2048);
user_pref("browser.cache.offline.enable", false);
user_pref("browser.download.manager.retention", 0);
user_pref("browser.formfill.enable", false);
user_pref("browser.history_expire_days", 0);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.migration.version", 1);
user_pref("browser.offline-apps.notify", false);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.search.update", false);
user_pref("browser.sessionstore.enabled", false);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.0.19");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnOpen", false);
user_pref("browser.urlbar.autocomplete.enabled", false);
user_pref("dom.disable_open_during_load", false);
user_pref("extensions.enabledItems", "{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.0.19");
user_pref("extensions.lastAppVersion", "3.0.19");
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("idle.lastDailyNotification", 1318419315);
user_pref("image.cache.size", 8192);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("layout.spellcheckDefault", 0);
user_pref("media.cache_size", 8192);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.type", 0);
user_pref("places.last_vacuum", 1318419315);
user_pref("pref.advanced.javascript.disable_button.advanced", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.promptOnSanitize", false);
user_pref("security.enable_java", false);
user_pref("security.warn_entering_weak", false);
user_pref("security.warn_viewing_mixed", false);
user_pref("signon.rememberSignons", false);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1321011005);
user_pref("xpinstall.whitelist.required", false);
