#!/bin/bash

build() {
    add_module 'dm-mod'
    add_module 'dm-mirror'

    add_binary 'dmraid'
    add_binary 'dmsetup'
    add_file "/usr/lib/device-mapper/libdmraid-events-isw.so"
    add_file "/usr/lib/udev/rules.d/10-dm.rules"
    add_file "/usr/lib/udev/rules.d/13-dm-disk.rules"
    add_file "/usr/lib/udev/rules.d/95-dm-notify.rules"
    add_file "/usr/lib/initcpio/udev/11-dm-initramfs.rules" "/usr/lib/udev/rules.d/11-dm-initramfs.rules"

    add_runscript
}

help() {
    cat <<HELPEOF
This hook loads the necessary modules for a dmraid root device.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
