#!/usr/bin/ash

run_hook() {
    modprobe -a -q dm-mod dm-mirror >/dev/null 2>&1
    msg ":: Activating dmraid arrays..."
    # prevent any event monitoring calls with -I
    if [ "$quiet" = "y" ]; then
        dmraid -ay -I -Z >/dev/null
    else
        dmraid -ay -I -Z
    fi
}

# vim: set ft=sh ts=4 sw=4 et:
