#!/bin/bash
#
# /usr/sbin/runjobs: run all executables in specified directory
#

if [ "$1" = "" ]; then
	echo "usage: $0 <dir>"
	exit 1
fi

cd $1 || exit 1

for file in ./*; do
	if [ -f $file ] && [ -x $file ]; then
		nice -n 19 $file
	fi
done

# End of file
