#!/bin/sh

port=gnome-keyring

# gconf schemas
SCHEMAS="`pkginfo -l $port | grep usr/etc/gconf/schemas/.*\.schemas$`"

for SCHEMA in $SCHEMAS
do
	export GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source`
	gconftool-2 --makefile-install-rule /$SCHEMA > /dev/null
done

# reload gconf caches
if [ ! -z "`pidof gconfd-2`" ]
then
	killall -HUP gconfd-2 > /dev/null
fi

# End of file
