#!/bin/sh
#
# /etc/rc.d/cups: start/stop/reload CUPS daemon
#

KEY=/etc/ssl/keys/cups.key
CRT=/etc/ssl/certs/cups.crt

case $1 in
start)
	if [ ! -s $KEY -o ! -s $CRT ]; then 
		/usr/bin/mksslcert $KEY $CRT
	fi
	/usr/sbin/cupsd
	;;
stop)
	killall -q /usr/sbin/cupsd
	;;
restart)
	$0 stop
	sleep 2
	$0 start
	;;
*)
	echo "Usage: $0 [start|stop|restart]"
	;;
esac

# End of file
