#!/bin/sh
#
# /etc/cron/weekly/syslog: rotate log files
#

/usr/sbin/rotatelog auth
/usr/sbin/rotatelog cron
/usr/sbin/rotatelog debug
/usr/sbin/rotatelog kernel
/usr/sbin/rotatelog mail
/usr/sbin/rotatelog messages

# End of file
