#!/bin/sh
#
# /etc/cron/daily/rdate: synchronize system clock
#
# Note: 
# If called with the -a option, rdate use the adjtime 
# system call instead of settimeofday to gradually skew 
# the local time to the remote time rather than just 
# hopping. See rdate(8) and adjtime(2).

#/usr/bin/rdate -nav pool.ntp.org

# End of file
