ChooseComponents {
    Title
    "Selecció de Components"

    Subtitle
    "Selecció dels components de la instal·lació."

    Caption
    "Seleccioni els components que desitja instal·lar i elimini els que\
     que no desitja que siguin instal·lats."

    Message
    "<%SpaceRequiredText%> d'espai necessari"

    DescriptionLabel
    "Descripció"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CopyFiles {
    Title
    "Instal·lant"

    Subtitle
    "Instal·lant <%AppName%>"

    Caption
    "Si us plau, espereu mentre s'instal·la <%AppName%> en el seu equip."

    Message
    ""

    FileLabel
    "<%Status%>"

    ProgressValue
    "<%InstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane1 {
    Caption
    "Llegenda aquí."

    Message
    "Missatge aquí."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane2 {
    Title
    "Ròtul"

    Subtitle
    "Subtítol"

    Caption
    "Llegenda"

    Message
    "Missatge"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane1 {
    Title
    "Ròtul"

    Subtitle
    "Subtítol"

    Caption
    "Llegenda"

    Message
    "Missatge"

    Text
    "Escriviu aquí el vostre missatge personalitzat."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

License {
    Title
    "Acord de Llicència"

    Subtitle
    "Si us plau, llegiu atentament l'acord de llicència."

    AcceptRadiobutton
    "Accepto els termes de l'acord de llicència."

    DeclineRadiobutton
    "NO accepto els termes de l'acord de llicència."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Readme {
    Title
    "Llegiu-me"

    Subtitle
    "Informació sobre <%AppName%>"

    Caption
    ""

    Message
    ""

    Text
    ""

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SelectDestination {
    Title
    "Elegiu el directori de destí"

    Subtitle
    "On desitgeu instal·lar <%AppName%>?"

    Caption
    "S'instal·larà <%AppName%> en el següent directori.\n\n Per instal·lar\
     en aquest directori, cliqueu Següent. Per instal·lar en un altre\
     directori, cliqueu Examinar i seleccioneu un altre directori."

    Message
    ""

    BrowseText
    "Cliqueu Següent per continuar. Si desitgeu seleccionar un\
    directori diferent, cliqueu Examinar."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    BrowseButton
    "<%Browse%>"

    DestinationLabel
    "Directori Destí"
}

SelectProgramFolder {
    Title
    "Seleccioni el Grup de Programes"

    Subtitle
    "Si us plau, seleccioni un grup de programes."

    Caption
    "S'instal·laran icones en el Grup de Programes següent. \
    Podeu escriure un nou nom de grup o seleccionar-ho\
    de la llista de grups existents. \
    Cliqueu Següent per continuar."

    Message
    ""

    ProgramFolderLabel
    "Grup de Programes:"

    FolderListLabel
    "Grups Existents:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    AllUsersCheckbutton
    "Crear un grup de programes per a tots els usuaris"
}

SetupComplete {
    Caption
    "InstallJammer Wizard Completat"

    Message
    "El Wizard InstallJammer ha instal·lat <%AppName%> correctament. \
     Cliqueu Finalitzar per a sortir d'aquest assistent."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SetupType {
    Title
    "Tipus d'Instal·lació"

    Subtitle
    "Seleccioni el tipus d'instal·lació més adient a les seves necessitats."

    Caption
    "Cliqueu el tipus d'instal·lació desitjada."

    Message
    ""

    DescriptionLabel
    "Descripció"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

StartCopyingFiles {
    Title
    "Iniciar la Còpia d'Arxius"

    Subtitle
    "Reviseu la configuració abans de copiar els arxius"

    Caption
    "S'ha reunit la informació necessària per a iniciar la còpia dels\
    arxius del programa. Si desitgeu revisar o canviar la configuració,\
    cliqueu Enrera. Si esteu conforme amb la configuració, cliqueu Següent\
    per a iniciar la còpia dels arxius."

    Message
    ""

    Text
    "Directori d'Instal·lació:
            <%InstallDir%>

    Tipus d'Instalació:
            <%InstallType%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Uninstall {
    Title
    "Desinstal·lar"

    Subtitle
    "Desinstal·lar <%AppName%>"

    Caption
    "<%GroupBeingUninstalledText%>"

    Message
    ""

    FileValue
    "<%Status%>"

    ProgressValue
    "<%UninstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallComplete {
    Caption
    "Desinstal·lació Completa"

    Message
    "<%AppName%> s'ha eliminat del seu sistema."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallDetails {
    Title
    "Detalls de la Desinstal·lació"

    Subtitle
    "Errors en l'eliminació"

    Caption
    "S'han produït els següents errors en el procés de desinstal·lació:"

    Message
    ""

    Text
    "<%Errors%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


UserInformation {
    Title
    "Informació d'Usuari"

    Subtitle
    "Si us plau, introduïu les vostres dades d'usuari."

    Caption
    "Si us plau, introduïu el nom de la vostra empresa."

    Message
    ""

    UserNameLabel
    "Nom d'Usuari:"

    CompanyLabel
    "Empresa:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


Welcome {
    Caption
    "Benvingut a l'Assistent InstallJammer per a <%AppName%>"

    Message
    "Aquest programa instal·larà <%AppName%> versió <%Version%> en el seu equip.\
    \n\nEs recomana tancar les aplicacions abans de continuar. \
    \n\nCliqueu Següent per continuar o Cancel·lar per sortir de la instal·lació."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}
