# options: -encoding utf-8

ChooseComponents {
    Title
    "Zvolte součásti"

    Subtitle
    "Zvolte součásti, které budou nainstalovány."

    Caption
    "Zvolte součásti, které chcete nainstalovat, a zrušte vybrání součástí,\
     které nechcete nainstalovat."

    Message
    "Vyžadováno <%SpaceRequiredText%> místa"

    DescriptionLabel
    "Popis"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CopyFiles {
    Title
    "Instalace"

    Subtitle
    "Instalace programu <%AppName%>"

    Caption
    "Prosím čekejte, dokud nebude program <%AppName%> nainstalován na váš počítač."

    Message
    ""

    FileLabel
    "<%Status%>"

    ProgressValue
    "<%InstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane1 {
    Caption
    "Titulek bude zde."

    Message
    "Zpráva bude zde."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane2 {
    Title
    "Nadpis"

    Subtitle
    "Podnadpis"

    Caption
    "Titulek"

    Message
    "Zpráva"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane1 {
    Title
    "Nadpis"

    Subtitle
    "Podnadpis"

    Caption
    "Titulek"

    Message
    "Zpráva"

    Text
    "Zde vložte svůj vlastní text."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

License {
    Title
    "Licenční ujednání"

    Subtitle
    "Následující licenční ujednání prosím čtěte pečlivě."

    Text
    "Zde vložte své licenční ujednání."

    AcceptRadiobutton
    "Přijímám podmínky licenčního ujednání."

    DeclineRadiobutton
    "Nepřijímám podmínky licenčního ujednání."

    NextButton
    "<%Yes%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%No%>"
}

Readme {
    Title
    "Informace ČtiMě"

    Subtitle
    "Informace ČtiMě pro <%AppName%>"

    Caption
    ""

    Message
    ""

    Text
    "Sem vložte vaše informace čtimě."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SelectDestination {
    Title
    "Zvolte cílové umístění"

    Subtitle
    "Kam má být program <%AppName%> nainstalován?"

    Caption
    "Program <%AppName%> bude nainstalován do následující složky.\n\nK instalaci\
     do této složky stiskněte Vpřed. K instalaci do jiné složky stiskněte\
     Procházet a zvolte jinou složku."

    Message
    ""

    BrowseText
    "K pokračování stiskněte Vpřed. Pokud chcete vybrat odlišnou složku,\
     stiskněte Procházet."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    BrowseButton
    "<%Browse%>"

    DestinationLabel
    "Cílová složka"
}

SelectProgramFolder {
    Title
    "Zvolte složku programu"

    Subtitle
    "Prosím zvolte složku programu."

    Caption
    "Instalátor přidá ikony programu do složky programu uvedené níže.\
     Můžete vepsat odlišný název složky nebo ji vybrat ze seznamu existujících složek.\
     K pokračování stiskněte Vpřed."

    Message
    ""

    ProgramFolderLabel
    "Složka programu:"

    FolderListLabel
    "Existující složky:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    AllUsersCheckbutton
    "Vytvořit složku programu pro všechny uživatele"
}

SetupComplete {
    Caption
    "Průvodce InstallJammer dokončen"

    Message
    "Průvodce InstallJammer úspěšně nainstaloval program <%AppName%>.\
     Stiskněte Dokončit pro ukončení průvodce."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SetupType {
    Title
    "Typ instalace"

    Subtitle
    "Zvolte typ instalace, který vám nejlépe vyhovuje."

    Caption
    "Klikněte na upřednostňovaný typ instalace."

    Message
    ""

    DescriptionLabel
    "Popis"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

StartCopyingFiles {
    Title
    "Spustit kopírování souborů"

    Subtitle
    "Zkontrolujte nastavení před kopírováním souborů"

    Caption
    "Instalátor má dostatek informací pro spustění kopírování souborů programu. Pokud\
     chcete zkontrolovat nebo změnit jakékoliv nastavení, stiskněte Zpět. Pokud jste\
     spokojeni s nastavením, stiskněte Vpřed pro spuštění kopírování souborů."

    Message
    ""

    Text
    "Instalační složka:
            <%InstallDir%>

    Typ instalace:
            <%InstallType%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Uninstall {
    Title
    "Odinstalace"

    Subtitle
    "Odinstalace programu <%AppName%>"

    Caption
    "<%GroupBeingUninstalledText%>"

    Message
    ""

    FileValue
    "<%Status%>"

    ProgressValue
    "<%UninstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallComplete {
    Caption
    "Odinstalace dokončena"

    Message
    "Program <%AppName%> byl odstraněn z vašeho systému."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallDetails {
    Title
    "Podrobnosti odinstalace"

    Subtitle
    "Během odstraňování došlo k chybám"

    Caption
    "Následující chyby nastaly během odstraňování:"

    Message
    ""

    Text
    "<%Errors%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


UserInformation {
    Title
    "Zákaznické informace"

    Subtitle
    "Prosím zadejte své informace."

    Caption
    "Prosím zadejte své jméno a název společnosti, pro kterou pracujete."

    Message
    ""

    UserNameLabel
    "Jméno zákazníka:"

    CompanyLabel
    "Společnost:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


Welcome {
    Caption
    "Vítejte v průvodci InstallJammer pro program <%AppName%>"

    Message
    "Na váš počítač bude nainstalován program <%AppName%> verze <%Version%>.\
    \n\nPřed pokračováním je doporučeno uzavřít všechny ostatní aplikace.\
    \n\nStiskněte Vpřed k pokračování nebo Zrušit k ukončení instalátoru."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

InstallPassword {
    Title
    "Heslo instalace"

    Subtitle
    "Tato instalace vyžaduje k pokračování heslo."

    Caption
    "Prosím zadejte heslo."

    Message
    ""

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}
