ChooseComponents {
    Title
    "Select Components"

    Subtitle
    "Select the components setup will install."

    Caption
    "Select the components you want to install and deselect the components\
     you do not want to install."

    Message
    "<%SpaceRequiredText%> of space required"

    DescriptionLabel
    "Description"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CopyFiles {
    Title
    "Installing"

    Subtitle
    "Installing <%AppName%>"

    Caption
    "Please wait while Setup installs <%AppName%> on your computer."

    Message
    ""

    FileLabel
    "<%Status%>"

    ProgressValue
    "<%InstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane1 {
    Caption
    "Caption goes here."

    Message
    "Message goes here."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane2 {
    Title
    "Title"

    Subtitle
    "Subtitle"

    Caption
    "Caption"

    Message
    "Message"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane1 {
    Title
    "Title"

    Subtitle
    "Subtitle"

    Caption
    "Caption"

    Message
    "Message"

    Text
    "Put your custom text here."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

License {
    Title
    "License Agreement"

    Subtitle
    "Please read the following license agreement carefully."

    Text
    "Put your license agreement here."

    AcceptRadiobutton
    "I accept the terms of the license agreement."

    DeclineRadiobutton
    "I do not accept the terms of the license agreement."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Readme {
    Title
    "Readme Information"

    Subtitle
    "Readme Information for <%AppName%>"

    Caption
    ""

    Message
    ""

    Text
    "Put your readme information here."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SelectDestination {
    Title
    "Choose Destination Location"

    Subtitle
    "Where should <%AppName%> be installed?"

    Caption
    "Setup will install <%AppName%> in the following folder.\n\nTo install\
     to this folder, click Next.  To install to a different folder, click\
     Browse and select another folder."

    Message
    ""

    BrowseText
    "To continue, click Next.  If you would like to select a different\
     folder, click Browse."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    BrowseButton
    "<%Browse%>"

    DestinationLabel
    "Destination Folder"
}

SelectProgramFolder {
    Title
    "Select Program Folder"

    Subtitle
    "Please select a program folder."

    Caption
    "Setup will add the program icons to the Program Folder listed below. \
     You may type a new folder name or select from the existing folders list. \
     Click Next to continue."

    Message
    ""

    ProgramFolderLabel
    "Program Folder:"

    FolderListLabel
    "Exising Folders:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    AllUsersCheckbutton
    "Create program folder for all users"
}

SetupComplete {
    Caption
    "InstallJammer Wizard Complete"

    Message
    "The InstallJammer Wizard has successfully installed <%AppName%>. \
     Click Finish to exit the wizard."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SetupType {
    Title
    "Setup Type"

    Subtitle
    "Select the setup type that best suits your needs."

    Caption
    "Click the type of Setup you prefer."

    Message
    ""

    DescriptionLabel
    "Description"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

StartCopyingFiles {
    Title
    "Start Copying Files"

    Subtitle
    "Review settings before copying files"

    Caption
    "Setup has enough information to start copying the program files.  If\
     you want to review or change any settings, click Back.  If you are\
     satisfied with the settings, click Next to begin copying files."

    Message
    ""

    Text
    "Install Directory:
            <%InstallDir%>

    Setup Type:
            <%InstallType%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Uninstall {
    Title
    "Uninstalling"

    Subtitle
    "Uninstalling <%AppName%>"

    Caption
    "<%GroupBeingUninstalledText%>"

    Message
    ""

    FileValue
    "<%Status%>"

    ProgressValue
    "<%UninstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallComplete {
    Caption
    "Uninstall Complete"

    Message
    "<%AppName%> has been removed from your system."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallDetails {
    Title
    "Uninstall Details"

    Subtitle
    "Errors occurred during removal"

    Caption
    "The following errors occurred during removal:"

    Message
    ""

    Text
    "<%Errors%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


UserInformation {
    Title
    "Customer Information"

    Subtitle
    "Please enter your information."

    Caption
    "Please enter your name and the name of the company for which you work."

    Message
    ""

    UserNameLabel
    "User Name:"

    CompanyLabel
    "Company:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


Welcome {
    Caption
    "Welcome to the InstallJammer Wizard for <%AppName%>"

    Message
    "This will install <%AppName%> version <%Version%> on your computer. \
    \n\nIt is recommended that you close all other applications before\
    continuing.\n\nClick Next to continue or Cancel to exit Setup."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

InstallPassword {
    Title
    "Install Password"

    Subtitle
    "This installation requires a password to continue."

    Caption
    "Please enter a password."

    Message
    ""

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}
