ChooseComponents {
    Title
    "Sélectionnez les composants"

    Subtitle
    "Sélectionnez les composants devant être installés."

    Caption
    "Sélectionner les composants à installer et déselectionner les composants à ne pas installer."

    Message
    "<%SpaceRequiredText%> d'espace requis"

    DescriptionLabel
    "Description"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CopyFiles {
    Title
    "Installation"

    Subtitle
    "Installation de <%AppName%>"

    Caption
    "Patientez pendant l'installation de <%AppName%> sur votre ordinateur."

    Message
    ""

    FileLabel
    "<%Status%>"

    ProgressValue
    "<%InstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane1 {
    Caption
    "Saisir la légende ici."

    Message
    "Saisir le message ici."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane2 {
    Title
    "Titre"

    Subtitle
    "Sous-titre"

    Caption
    "Légende"

    Message
    "Message"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane1 {
    Title
    "Titre"

    Subtitle
    "Sous-titre"

    Caption
    "Légende"

    Message
    "Message"

    Text
    "Saisissez votre texte personnalisé ici."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

License {
    Title
    "Accord de licence"

    Subtitle
    "Veuillez lire attentivement l'accord de licence suivant SVP."

    AcceptRadiobutton
    "J'accepte les termes de cet accord de licence."

    DeclineRadiobutton
    "Je n'accepte pas les termes de cet accord de licence."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Readme {
    Title
    "Readme"

    Subtitle
    "Readme pour <%AppName%>"

    Caption
    ""

    Message
    ""

    Text
    ""

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SelectDestination {
    Title
    "Sélectionnez le répertoire d'installation"

    Subtitle
    "Où installer <%AppName%> ?"

    Caption
    "L'installation de <%AppName%> s'effectuera dans le répertoire suivant.\n\nPour installer\
     dans ce répertoire, cliquez sur le bouton SUIVANT.\n\nPour installer dans un autre répertoire, cliquez\
     sur le bouton PARCOURIR et sélectionnez un autre répertoire."

    Message
    ""

    BrowseText
    "Pour continuer, cliquez sur SUIVANT.  Pour sélectionner un répertoire\
     différent, cliquez sur PARCOURIR."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    BrowseButton
    "<%Browse%>"

    DestinationLabel
    "Répertoire d'installation"
}

SelectProgramFolder {
    Title
    "Sélectionnez le dossier Programme"

    Subtitle
    "Sélectionnez un dossier Programme SVP."

    Caption
    "L'installation ajoutera les icônes de programme au dossier Programme affiché ci-dessous. \
     Vous pouvez saisir un nouveau nom de dossier ou en sélectionner un dans la liste des dossiers existants. \
     Cliquez sur SUIVANT pour continuer."

    Message
    ""

    ProgramFolderLabel
    "Dossier Programme:"

    FolderListLabel
    "Dossiers existants :"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    AllUsersCheckbutton
    "Créer le dossier programme pour tous les utilisateurs"
}

SetupComplete {
    Caption
    "L'assistant InstallJammer est terminé"

    Message
    "L'assistant InstallJammer a installé <%AppName%> avec succès. \
     Cliquez sur TERMINER pour quitter l'assistant."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SetupType {
    Title
    "Type d'installation"

    Subtitle
    "Sélectionnez le type d'installation convenant le mieux à vos besoins."

    Caption
    "Cliquez sur le type d'installation que vous souhaitez."

    Message
    ""

    DescriptionLabel
    "Description"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

StartCopyingFiles {
    Title
    "Copie des fichiers"

    Subtitle
    "Contrôle du paramétrage avant la copie de fichiers"

    Caption
    "L'installeur a maintenant assez d'informations pour commencer à copier les fichiers.  Si\
     vous voulez revoir ou modifier le paramétrage, cliquez sur PRECEDENT.  Si vous êtes\
     satisfait du paramétrage, cliquez sur suivant pour commencer à copier les fichiers."

    Message
    ""

    Text
    "Répertoire d'installation:
            <%InstallDir%>

    Type d'installation:
            <%InstallType%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Uninstall {
    Title
    "Désinstallation"

    Subtitle
    "Désinstallation de <%AppName%>"

    Caption
    "<%GroupBeingUninstalledText%>"

    Message
    ""

    FileValue
    "<%Status%>"

    ProgressValue
    "<%UninstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallComplete {
    Caption
    "Désinstallation terminée"

    Message
    "<%AppName%> a été désinstallé de votre système."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallDetails {
    Title
    "Details de la désinstallation"

    Subtitle
    "Des erreurs sont apparues pendant la désinstallation"

    Caption
    "Les erreurs suivantes sont apparues pendant la désinstallation:"

    Message
    ""

    Text
    "<%Errors%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


UserInformation {
    Title
    "Information client"

    Subtitle
    "Saisissez vos informations SVP."

    Caption
    "Saisissez votre nom et votre société."

    Message
    ""

    UserNameLabel
    "Nom:"

    CompanyLabel
    "Société:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


Welcome {
    Caption
    "Bienvenue dans l'assistant d'installation InstallJammer pour <%AppName%>"

    Message
    "Ceci installera <%AppName%> version <%Version%> sur votre ordinateur. \
    \n\nIl est recommandé de fermer toutes les autres applications avant\
    de continuer.\n\nCliquez sur SUIVANT pour continuer ou ANNULER pour quitter l'installation."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}
