ChooseComponents {
    Title
    "Komponensek kiválasztása"

    Subtitle
    "Válassza ki a telepítend\u0151 komponenseket."

    Caption
    "Válassza ki azokat a komponenseket, amelyeket fel akar telepíteni,\
     és ne válassza ki azokat, amelyeket nem akar telepíteni."

    Message
    "<%SpaceRequiredText%> szabad hely szükséges"

    DescriptionLabel
    "Leírás"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CopyFiles {
    Title
    "Telepítés"

    Subtitle
    "<%AppName%> telepítése"

    Caption
    "Kérem várjon, amíg a Telepít\u0151 a <%AppName%> programot feltelepíti a gépére."

    Message
    ""

    FileLabel
    "<%Status%>"

    ProgressValue
    "<%InstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane1 {
    Caption
    "A fejléc jön ide."

    Message
    "Az üzenet jön ide."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane2 {
    Title
    "Cím"

    Subtitle
    "Alcím"

    Caption
    "Leírás"

    Message
    "Üzenet"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane1 {
    Title
    "Cím"

    Subtitle
    "Alcím"

    Caption
    "Leírás"

    Message
    "Üzenet"

    Text
    "A saját szövegedet rakd ide."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

License {
    Title
    "Licensz elfogadása"

    Subtitle
    "Kérem olvassa el figyelmesen a következ\u0151 licensz megállapodást."

    AcceptRadiobutton
    "Elfogadom a licensz megállapodás feltételeit."

    DeclineRadiobutton
    "Nem fogadom el a licensz megállapodás feltételeit."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Readme {
    Title
    "Olvassa el információk"

    Subtitle
    "Olvassa el információk a <%AppName%> alkalmazáshoz"

    Caption
    ""

    Message
    ""

    Text
    ""

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SelectDestination {
    Title
    "Válassza ki a cél könyvtárat"

    Subtitle
    "Hova kellene a <%AppName%> alkalmazást telepíteni?"

    Caption
    "A telepít\u0151 a <%AppName%> programot a következ\u0151 könyvtárba telepíti.\n\n
     Ahhoz, hogy ebbe könyvtárba kerüljön kattintson a <%Next%> gombra\
     Ahhoz, hogy más könyvtárba kerüljön kattintson a <%Browse%> gombra."

    Message
    ""

    BrowseText
    "A folytatáshoz nyomja meg a <%Next%> gombot. \
     Ha másik könyvtárat szeretne kiválasztani nyomja meg a <%Browse%> gombot."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    BrowseButton
    "<%Browse%>"

    DestinationLabel
    "Cél könyvtár"
}

SelectProgramFolder {
    Title
    "Program mappa kiválasztás"

    Subtitle
    "Kérem válassza ki a program mappát!"

    Caption
    "A telepít\u0151 a program ikonokat a lentebb listázott Program mappához fogja hozzáadni. \
	 Megváltoztathatja az új mappa nevét, vagy kiválaszthat egy már létez\u0151t a listáról. \
     Kattintson a <%Next%> gombra a folytatáshoz."

    Message
    ""

    ProgramFolderLabel
    "Program mappa:"

    FolderListLabel
    "Létez\u0151 mappák:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    AllUsersCheckbutton
    "Létrehozza a program mappát az összes felhasználónak?"
}

SetupComplete {
    Caption
    "InstallJammer Varázsló befejez\u0151dött"

    Message
    "Az InstallJammer Varázsló sikeresen telepítette a <%AppName%> alkalmazást. \
	 Kattintson a <%Finish%> gombra ahhoz, hogy kilépjen a varázslóból."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SetupType {
    Title
    "Telepítés típusa"

    Subtitle
    "Válassza ki az Önnek legjobban megfelel\u0151 telepítési módot."

    Caption
    "Válassza ki a kívánt telepítési típust!"

    Message
    ""

    DescriptionLabel
    "Leírás"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

StartCopyingFiles {
    Title
    "Állományok másolásának elkezdése"

    Subtitle
    "Tekintse át a beállításokat, miel\u0151tt átmásolnánk az állományokat!"

    Caption
    "A telepít\u0151nek elég információja van ahhoz, hogy a program állományait\
	elkezdje másolni. Ha meg akarja nézni vagy változtatni a beállításokat,\
	akkor kattintson a <%Back%> gombra. Ha elégedett a beállításokkal, akkor\
	kattintson a <%Next%> gombra, hogy elkezd\u0151djön a fájlok másolása."

    Message
    ""

    Text
    "Telepítési könyvtár:
            <%InstallDir%>

    Telepítés típusa:
            <%InstallType%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Uninstall {
    Title
    "Eltávolítás"

    Subtitle
    "A <%AppName%> alkalmazás eltávolítása"

    Caption
    "<%GroupBeingUninstalledText%>"

    Message
    ""

    FileValue
    "<%Status%>"

    ProgressValue
    "<%UninstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallComplete {
    Caption
    "Eltávolítás befejez\u0151dött"

    Message
    "A <%AppName%> alkalmazás el lett távolítva a rendszerér\u0151l."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallDetails {
    Title
    "Eltávolítás részletei"

    Subtitle
    "Az eltávolítás alatt hiba lépett fel!"

    Caption
    "A következ\u0151 hibák léptek fel az eltávolítás alatt:"

    Message
    ""

    Text
    "<%Errors%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


UserInformation {
    Title
    "Vásárlói információk"

    Subtitle
    "Kérem írja ide az információkat."

    Caption
    "Kérem írja be a nevét és a munkahelyének nevét."

    Message
    ""

    UserNameLabel
    "Felhasználó neve:"

    CompanyLabel
    "Cég:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


Welcome {
    Caption
    "Isten hozta a <%AppName%> InstallJammer Varázslójában"

    Message
    "Ez a <%AppName%> alkalmazás <%Version%> verzióját fogja telepíteni\
	a számítógépére.\n\n Javasoljuk, hogy zárjon be minden alkalmazást,\
	miel\u0151tt folytatná.\n\n Kattintson a <%Next%> gombra a folytatáshoz\
	vagy a <%Cancel%> gombra kilépéshez."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

InstallPassword {
    Title
    "Jelszavas telepítés"

    Subtitle
    "Ez a telepítés egy jelszót igényel a folytatáshoz."

    Caption
    "Kérem gépelje be a jelszót."

    Message
    ""

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}
