ChooseComponents {
    Title
    "Selezionare le parti"

    Subtitle
    "Selezionare le parti che saranno installate dal programma."

    Caption
    "Selezionare le parti che si desidera installare e deselezionare le\
     parti che non si desidera installare."

    Message
    "<%SpaceRequiredText%> di spazio richiesto"

    DescriptionLabel
    "Descrizione"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CopyFiles {
    Title
    "Installazione in corso"

    Subtitle
    "Installazione di <%AppName%>"

    Caption
    "Si prega di attendere mentre il programma installa <%AppName%> sul\
     computer."

    Message
    ""

    FileLabel
    "<%Status%>"

    ProgressValue
    "<%InstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane1 {
    Caption
    "La didascalia va qui."

    Message
    "Il messaggio va qui."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane2 {
    Title
    "Titolo"

    Subtitle
    "Sottotitolo"

    Caption
    "Didascalia"

    Message
    "Messaggio"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane1 {
    Title
    "Titolo"

    Subtitle
    "Sottotitolo"

    Caption
    "Didascalia"

    Message
    "Messaggio"

    Text
    "Inserire qui il testo personalizzato."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

License {
    Title
    "Contratto di Licenza"

    Subtitle
    "Si prega di leggere attentamente il contratto di licenza che segue."

    AcceptRadiobutton
    "Accetto le condizioni del Contratto di licenza."

    DeclineRadiobutton
    "Non accetto le condizioni del Contratto di licenza."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Readme {
    Title
    "Informazioni da leggere"

    Subtitle
    "Informazioni da leggere riguardo a <%AppName%>"

    Caption
    ""

    Message
    ""

    Text
    ""

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SelectDestination {
    Title
    "Scegliere la directory  di destinazione"

    Subtitle
    "Dove si desidera installare <%AppName%>?"

    Caption
    "Il programma di installazione installerà <%AppName%> nella seguente\
     cartella.\n\nPer installare in questa cartella, premere su Avanti. \
     Per installare in una cartella diversa, premere su Sfoglia e\
     selezionare un'altra cartella."

    Message
    ""

    BrowseText
    "Per proseguire, premere su Avanti. Se si desidera selezionare una\
     cartella diversa, premere su Sfoglia."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    BrowseButton
    "<%Browse%>"

    DestinationLabel
    "Cartella di destinazione"
}

SelectProgramFolder {
    Title
    "Selezionare la cartella del programma"

    Subtitle
    "Si prega di selezionare la cartella del programma."

    Caption
    "Il programma di installazione aggiungerà le icone del programma nella\
     cartella elencata sotto. \
     Si può inserire il nome di una nuova cartella o selezionarla dalla\
     lista delle cartelle esistenti. \
     Premere su Avanti per proseguire."

    Message
    ""

    ProgramFolderLabel
    "Cartella del programma:"

    FolderListLabel
    "Cartelle esistenti:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    AllUsersCheckbutton
    "Crea la cartella del programma per tutti gli utenti"
}

SetupComplete {
    Caption
    "Autocomposizione di InstallJammer completata"

    Message
    "L'autocomposizione di InstallJammer ha installato <%AppName%> con\
     successo. Premere su Fine per uscire dall'autocomposizione."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SetupType {
    Title
    "Tipologia di installazione"

    Subtitle
    "Selezionare la tipologia di installazione più adatta alle proprie esigenze."

    Caption
    "Scegliere la tipologia di installazione che si preferisce."

    Message
    ""

    DescriptionLabel
    "Descrizione"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

StartCopyingFiles {
    Title
    "Inizio della copia dei file"

    Subtitle
    "Controllo delle impostazioni prima della copia dei file"

    Caption
    "Il programma di installazione ha sufficienti informazioni per iniziare\
     la copia dei file del programma. Se si desidera controllare o\
     modificare le impostazioni, premere Indietro. Se si è soddisfatti\
     delle impostazioni, premere Avanti per iniziare a copiare i file."

    Message
    ""

    Text
    "Directory di installazione:
            <%InstallDir%>

    Tipologia di installazione:
            <%InstallType%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Uninstall {
    Title
    "Disinstallazione in corso"

    Subtitle
    "Disinstallazione di <%AppName%>"

    Caption
    "<%GroupBeingUninstalledText%>"

    Message
    ""

    FileValue
    "<%Status%>"

    ProgressValue
    "<%UninstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallComplete {
    Caption
    "Disinstallazione completata"

    Message
    "<%AppName%> è stato rimosso dal sistema."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallDetails {
    Title
    "Dettagli della disinstallazione"

    Subtitle
    "Durante la rimozione sono occorsi degli errori"

    Caption
    "I seguenti errori sono occorsi durante la rimozione:"

    Message
    ""

    Text
    "<%Errors%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


UserInformation {
    Title
    "Informazioni sul cliente"

    Subtitle
    "Si prega di inserire le informazioni."

    Caption
    "Si prega di inserire il proprio nome e il nome della società per cui\
     si lavora."

    Message
    ""

    UserNameLabel
    "Nome dell'utente:"

    CompanyLabel
    "Società:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


Welcome {
    Caption
    "Benvenuti nell'autocomposizione di InstallJammer per <%AppName%>"

    Message
    "Si sta per installare <%AppName%> nella versione <%Version%>\
     sul computer. \
     \n\nE' consigliata la chiusura di tutte le altre applicazioni prima di\
     proseguire.\n\nPremere su Avanti per continuare o su Annulla per uscire dall'installazione."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

InstallPassword {
    Title
    "Parola chiave di installazione"

    Subtitle
    "L'installazione richiede una parola chiave per proseguire."

    Caption
    "Si prega di inserire la parola chiave."

    Message
    ""

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}
