ChooseComponents {
    Title
    "Pasirenkamasis ádiegimas"

    Subtitle
    "Pasirinkite komponentus kuriuos diegimo programa ádiegs."

    Caption
    "Paþymëkite komponentus kuriuos norite ádiegti ir atþymëkite\
     tuos kuriuos nenorite ádiegti."


    Message
    "Reikës <%SpaceRequiredText%> talpos"

    DescriptionLabel
    "Apraðymas"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CopyFiles {
    Title
    "Diegiama"

    Subtitle
    "Diegiama <%AppName%>"

    Caption
    "Praðom palaukti kol diegimo programa ádiegs <%AppName%> á jûsø kompiuterá."

    Message
    ""

    FileLabel
    "<%Status%>"

    ProgressValue
    "<%InstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane1 {
    Caption
    "Áveskite pavadinimà."

    Message
    "Áveskite praneðimà."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane2 {
    Title
    "Antraðtë"

    Subtitle
    "Paantraðtë"

    Caption
    "Pavadinimas"

    Message
    "Praneðimas"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane1 {
    Title
    "Antraðtë"

    Subtitle
    "Paantraðtë"

    Caption
    "Pavadinimas"

    Message
    "Praneðimas"

    Text
    "Áveskite pasirinktà teskta."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

License {
    Title
    "Sutikimas su licencija"

    Subtitle
    "raðom perskaityti ðá sutikimà su licencija."

    Text
    "Patalpinkite èia savo licencijà."

    AcceptRadiobutton
    "Að sutinku su licencija."

    DeclineRadiobutton
    "Að nesutinku su licencija."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Readme {
    Title
    "Skaityti daugiau informacijos"

    Subtitle
    "Skaityti daugiau informacijos apie <%AppName%>"

    Caption
    ""

    Message
    ""

    Text
    "Patalpinkite informacija."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SelectDestination {
    Title
    "Pasirinkite paskirties vietà"

    Subtitle
    "Kur turëtø bûti <%AppName%> ádiegta?"

    Caption
     "Diegimo programa ádiegs <%AppName%> á ðá katalogà.\n\nTam kad instaliuoti\
     á ðá katalogà, paspauskite <%Next%>.\n\nÁdiegimui á kita katalogà,\
     paspauskite <%Browse%> ir pasirinkite kità katalogà."

    Message
    ""

    BrowseText
    "Tam kad instaliuoti á ðá katalogà, paspauskite <%Next%>. Ádiegimui á
     kita katalogà, paspauskite <%Browse%> ir pasirinkite kità katalogà."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    BrowseButton
    "<%Browse%>"

    DestinationLabel
    "Paskirties katalogas"
}

SelectProgramFolder {
    Title
    "Pasirinkite programos katalogà"

    Subtitle
    "Praðom pasirinkite programos katalogà"

    Caption
    "Diegimo programa ákels programos ikonas á programø katalogà pavaizduotà\
     apaèioje.  Galite ávesti naujà katalogo pavadinimà arba pasirinkti ið\
     esanèiø.  Norëdami tæsti <%Next%>."

    Message
    ""

    ProgramFolderLabel
    "Programos katalogas:"

    FolderListLabel
    "Esantys katalogai:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    AllUsersCheckbutton
    "Sukurti programos katalogus visiems vartotojams"
}

SetupComplete {
    Caption
    "InstallJammer vedlys pabaigë darbà"

    Message
    "Diegimo programa baigë diegti <%AppName%> á jûsø kompiuterá.  Paspauskite\
    <%Finish%>, kad uþbaigti diegimà."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SetupType {
    Title
    "Diegimo tipas"

    Subtitle
    "Pasirinkite diegimo tipà kurio pageidaujate."

    Caption
    "Pasirinkite diegimo tipà kurio pageidaujate."

    Message
    ""

    DescriptionLabel
    "Apraðymas"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

StartCopyingFiles {
    Title
    "Pradedamas failø kopijavimas"

    Subtitle
    "Perþiûrëkite nustatymus prieð pradedant kopijuoti failus"

    Caption
    "Diegimo programa turi pakankamai informacijos, kad pradëti kopijuoti programos failus.\
     Jei norite perþiûrëti arba pakeisti nustatymus, spauskite <%Back%>. Jei nustatymai\
     tenkina, spauskite <%Next%>, kad pradëti kopijuoti failus."

    Message
    ""

    Text
    "Diegimo katalogas:
            <%InstallDir%>

    Diegimo tipas:
            <%InstallType%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Uninstall {
    Title
    "Uninstalling"

    Subtitle
    "Paðalinama <%AppName%>"

    Caption
    "<%GroupBeingUninstalledText%>"

    Message
    ""

    FileValue
    "<%Status%>"

    ProgressValue
    "<%UninstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallComplete {
    Caption
    "Programos paðalinimas baigtas"

    Message
    "<%AppName%> buvo paðalinta ið jûsø sistemos."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallDetails {
    Title
    "Programos paðalinimas iðsamiau"

    Subtitle
    "Klaidos atsitikusios per programos paðalinimà"

    Caption
    "Klaidos atsitikusios per programos paðalinimà:"

    Message
    ""

    Text
    "<%Errors%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


UserInformation {
    Title
    "Vartotojo informacija"

    Subtitle
    "Praðome ávesti savo informacijà."

    Caption
    "Áveskite savo vardà ir organizacijà kurioje dirbate."

    Message
    ""

    UserNameLabel
    "Vartotojo vardas:"

    CompanyLabel
    "Organizacija:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


Welcome {
    Caption
    "Sveiki atvyke á <%AppName%> diegimo programà."

    Message
    "Pabrëþtinai patartina iðeiti ið visø Windows programø kurias esate\
     pasileidæ. Spauskite <%Next%> tam, kad tæsti diegimà."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

InstallPassword {
    Title
    "Diegimo slaptaþodis"

    Subtitle
    "Ðiam diegimui reikia slaptaþodþio."

    Caption
    "Praðom ávesti slaptaþodá."

    Message
    ""

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}
