ChooseComponents {
    Title
    "Selecteer Componenten"

    Subtitle
    "Selecteer de componenten die het installatie programma zal installeren."

    Caption
    "Selecteer de componenten die u wilt installeren en deselecteer de componenten\
     die u niet wilt installeren."

    Message
    "<%SpaceRequiredText%> aan ruimte benodigd"

    DescriptionLabel
    "Omschrijving"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CopyFiles {
    Title
    "Installeren"

    Subtitle
    "<%AppName%> installeren"

    Caption
    "Een ogenblik geduld terwijl <%AppName%> wordt geïnstalleerd op uw computer."

    Message
    ""

    FileLabel
    "<%Status%>"

    ProgressValue
    "<%InstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane1 {
    Caption
    "Bijschrift hier."

    Message
    "Bericht hier."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane2 {
    Title
    "Titel"

    Subtitle
    "Ondertitel"

    Caption
    "Bijschrift"

    Message
    "Bericht"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane1 {
    Title
    "Titel"

    Subtitle
    "Ondertitel"

    Caption
    "Bijschrift"

    Message
    "Bericht"

    Text
    "Zet uw eigen tekst hier."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

License {
    Title
    "Licentie Overeenkomst"

    Subtitle
    "Lees de licentie overeenkomst aandachtig."

    AcceptRadiobutton
    "Ik ga akkoord met de licentie overeenkomst."

    DeclineRadiobutton
    "Ik ga NIET akkoord met de licentie overeenkomst."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "Stop Installatie"
}

Readme {
    Title
    "Readme Informatie"

    Subtitle
    "Readme Informatie voor <%AppName%>"

    Caption
    ""

    Message
    ""

    Text
    ""

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SelectDestination {
    Title
    "Kies de installatie map"

    Subtitle
    "Waar moet <%AppName%> worden geïnstalleerd?"

    Caption
    "Dit installatie programma zal <%AppName%> in de onderstaande map installeren."


    Message
    ""

    BrowseText
    "Als u de installatie locatie wilt wijzigen klikt u op 'Selecteer map' en selecteert u een nieuwe locatie.
     Om verder te gaan met het installatieproces klikt u op Volgende."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    BrowseButton
    "<%Browse%>"

    DestinationLabel
    "Installatie map"
}

SelectProgramFolder {
    Title
    "Selecteer Programma Map"

    Subtitle
    "U kunt de Programma map selecteren."

    Caption
    "Het installatie programma zal de programma iconen toevoegen aan de onderstaande Programma map. \
     U kunt een nieuwe map aanmaken of een bestaande map selecteren uit de lijst. \
     Klik op Volgende om door te gaan."

    Message
    ""

    ProgramFolderLabel
    "Programma map:"

    FolderListLabel
    "Huidige mappen:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    AllUsersCheckbutton
    "Maak programma map voor alle gebruikers"
}

SetupComplete {
    Caption
    "Installatie Programma Afgerond"

    Message
    "Het installatie programma heeft <%AppName%> succesvol geïnstalleerd. \
     Klik op <%Finish%> om het installatie programma te sluiten."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SetupType {
    Title
    "Setup Type"

    Subtitle
    "Kies het type setup dat u prefereerd."

    Caption
    "Kies het type setup dat u prefereerd."

    Message
    ""

    DescriptionLabel
    "Omschrijving"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

StartCopyingFiles {
    Title
    "Start Kopiëren Bestanden"

    Subtitle
    "Bekijk uw instellingen voordat het installeren begint"

    Caption
    "Het installatie programma heeft genoeg informatie om het kopiëren te starten. \
     Als u de instellingen wilt bekijken of wijzigen kunt op <%Back%> klikken.  Als u\
     tevreden bent met de instellingen klikt u op <%Next%> om het kopiëren te starten."

    Message
    ""

    Text
    "Installatie directory:
            <%InstallDir%>

    Setup type:
            <%InstallType%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Uninstall {
    Title
    "Deïnstalleren"

    Subtitle
    "<%AppName%> deïnstalleren"

    Caption
    "<%GroupBeingUninstalledText%>"

    Message
    ""

    FileValue
    "<%Status%>"

    ProgressValue
    "<%UninstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallComplete {
    Caption
    "Deïnstallatie afgerond"

    Message
    "<%AppName%> is van uw systeem verwijderd."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallDetails {
    Title
    "Deïnstallatie Details"

    Subtitle
    "Er hebben zich fouten voorgedaan tijdens de deïnstallatie"

    Caption
    "De volgende fouten hebben zicht voorgedaan tijdens de deïnstallatie:"

    Message
    ""

    Text
    "<%Errors%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


UserInformation {
    Title
    "Gebruikers Informatie"

    Subtitle
    "Vul uw informatie in."

    Caption
    "Vul uw naam en uw bedrijfsnaam in."

    Message
    ""

    UserNameLabel
    "Naam:"

    CompanyLabel
    "Bedrijfsnaam:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


Welcome {
    Caption
    "Welkom bij het <%AppName%> installatie programma.  Dit programma zal\
     <%AppName%> op uw computer installeren."

    Message
    "Het is aan te raden alle overige applicaties te sluiten alvorens\
     verder te gaan met deze installatie.\n\nKlik op <%Next%> om verder\
     te gaan of op <%Cancel%> om deze installatie af te breken"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

InstallPassword {
    Title
    "Installatie Wachtwoord"

    Subtitle
    "Deze installatie vereist een wachtwoord om door te kunnen gaan."

    Caption
    "Vul uw wachtwoord in."

    Message
    ""

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}
