# options: -encoding utf-8

ChooseComponents {
    Title
    "Wybierz komponenty"

    Subtitle
    "Wybierz komponenty do zainstalowania."

    Caption
    "Zaznacz komponenty, które chcesz zainstalować, a odznacz te,\
     których nie chcesz instalować."

    Message
    "Wymagane miejsce na dysku: <%SpaceRequiredText%>"

    DescriptionLabel
    "Opis"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CopyFiles {
    Title
    "Instalowanie"

    Subtitle
    "Instalowanie <%AppName%>"

    Caption
    "Proszę czekać podczas, gdy Instalator instaluje <%AppName%> na twoim komputerze."

    Message
    ""

    FileLabel
    "<%Status%>"

    ProgressValue
    "<%InstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane1 {
    Caption
    "Caption goes here."

    Message
    "Message goes here."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane2 {
    Title
    "Tytuł"

    Subtitle
    "Podtytuł"

    Caption
    "Nagłówek"

    Message
    "Wiadomość"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane1 {
    Title
    "Tytuł"

    Subtitle
    "podtytuł"

    Caption
    "Nagłówek"

    Message
    "Wiadomość"

    Text
    "Tutaj wpisuj swój tekst."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

License {
    Title
    "Warunki licencji"

    Subtitle
    "Proszę uważnie przeczytać poniższą licencję."

    AcceptRadiobutton
    "Akceptuję warunki licencji."

    DeclineRadiobutton
    "Nie akceptuję warunków licencji."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Readme {
    Title
    "Informacje Readme"

    Subtitle
    "Informacje Readme dla <%AppName%>"

    Caption
    ""

    Message
    ""

    Text
    ""

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SelectDestination {
    Title
    "Wybierz folder docelowy"

    Subtitle
    "Gdzie zainstalować <%AppName%>?"

    Caption
    "Instalator zainstaluje <%AppName%> w wybranym folderze.\n\nAby instalować\
     w tym folderze, kliknij Dalej.  Aby zainstalować w innym folderze, kliknij\
     Przeglądaj i wybierz inny folder."

    Message
    ""

    BrowseText
    "Aby kontynuować, kliknij Dalej.  Jeśli chcesz wybrać inny folder,\
     kliknij Przeglądaj."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    BrowseButton
    "<%Browse%>"

    DestinationLabel
    "Folder docelowy"
}

SelectProgramFolder {
    Title
    "Wybierz folder programu"

    Subtitle
    "Przoszę wybrać folder dla programu."

    Caption
    "Instalator doda ikonki programu w folderze aplikacji wybranym poniżej. \
     Możesz wprowadzić nową nazwę folderu lub wybrać z listy już istniejących. \
     Kliknij Dalej, aby kontynuować."

    Message
    ""

    ProgramFolderLabel
    "Folder programu:"

    FolderListLabel
    "Istniejące foldery:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    AllUsersCheckbutton
    "Utwórz folder programu dla wszystkich użytkowników"
}

SetupComplete {
    Caption
    "InstallJammer - Instalacja zakończona"

    Message
    "Instalator InstallJammer zainstalował pomyślnie <%AppName%>. \
     Kliknij Zakończ, aby opuścić instalator."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SetupType {
    Title
    "Typ instalacji"

    Subtitle
    "Wybierz typ instalacji, który Ci odpowiada."

    Caption
    "Kliknij preferowany typ instalacji."

    Message
    ""

    DescriptionLabel
    "Opis"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

StartCopyingFiles {
    Title
    "Rozpocznij kopiowanie plików"

    Subtitle
    "Pokaż ustawienia przed rozpoczęciem kopiowania plików"

    Caption
    "Instalator posiada już wszystkie informacje potrzebnedo rozpoczęcia\
     kopiowania plików. Jeśli chcesz zobaczyć ustawienia lub zmienić je,\
     kliknij Wstecz. Jeśli jesteś pewien ustawień, kliknij Dalej, aby\
     rozpocząć kopiowanie plików."

    Message
    ""

    Text
    "Folder docelowy:
            <%InstallDir%>

    Typ instalacji:
            <%InstallType%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Uninstall {
    Title
    "Usuwanie"

    Subtitle
    "Deinstalacja <%AppName%>"

    Caption
    "<%GroupBeingUninstalledText%>"

    Message
    ""

    FileValue
    "<%Status%>"

    ProgressValue
    "<%UninstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallComplete {
    Caption
    "Usuwanie zakończone"

    Message
    "Usunięto pomyślnie <%AppName%> z twojego systemu."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallDetails {
    Title
    "Detale deinstalacji"

    Subtitle
    "Błędy podczas usuwania"

    Caption
    "Napotkano następujące błędy podczas usuwania:"

    Message
    ""

    Text
    "<%Errors%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


UserInformation {
    Title
    "Informacje o kliencie"

    Subtitle
    "Proszę wpisać swoje dane."

    Caption
    "Proszę podać nazwisko i nazwę firmy, dla której pracujesz."

    Message
    ""

    UserNameLabel
    "Nazwa użytkownika:"

    CompanyLabel
    "Firma:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


Welcome {
    Caption
    "Witamy w InstallJammer - instalatorze dla <%AppName%>"

    Message
    "Zainstaluje on <%AppName%> w wersji <%Version%> na twoim komputerze. \
    \n\nZalecane jest zamknięcie wszystkich programów przed instalacją. \
    \n\nKliknij Dalej, aby kontynuować lub Anuluj, aby opuścić instalator."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}
