ChooseComponents {
    Title
    "Selecionar Componentes"

    Subtitle
    "Selecione os componentes que seão instalados."

    Caption
    "Selecione os componentes que você quer instalar e deselecione os componentes\
     que você não quer instalar."

    Message
    "<%SpaceRequiredText%> de espaço é necessário"

    DescriptionLabel
    "Descrição"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CopyFiles {
    Title
    "Instalando"

    Subtitle
    "Instalando <%AppName%>"

    Caption
    "Por favor, aguarde enquanto o programa <%AppName%> é instalado em seu computador."

    Message
    ""

    FileLabel
    "<%Status%>"

    ProgressValue
    "<%InstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane1 {
    Caption
    "Caption irá aqui."

    Message
    "Mensagem irá aqui."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane2 {
    Title
    "Título"

    Subtitle
    "Subtítulo"

    Caption
    "Caption"

    Message
    "Mensagem"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane1 {
    Title
    "Título"

    Subtitle
    "Subtítulo"

    Caption
    "Caption"

    Message
    "Mensagem"

    Text
    "Coloque seu texto personalizado aqui."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

License {
    Title
    "Concordância com a Licença"

    Subtitle
    "Por favor, leia os termos da licença cuidadosamente."

    AcceptRadiobutton
    "Eu concordo os termos da licença."

    DeclineRadiobutton
    "Eu não concordo com os termos da licença."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Readme {
    Title
    "Informações do Readme"

    Subtitle
    "Informações do Readme para <%AppName%>"

    Caption
    ""

    Message
    ""

    Text
    ""

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SelectDestination {
    Title
    "Escolha a localização de destino"

    Subtitle
    "Onde o <%AppName%> deverá ser instalado?"

    Caption
    "A Instalação irá instalar <%AppName%> na seguinte pasta.\n\nPara instalar\
     nesta pasta, clique em Próximo.  Para instalar em uma pasta diferente, clique\
     em Procurar e selecione outra pasta."

    Message
    ""

    BrowseText
    "Para continuar, clique em Próximo.  Se você deseja selecionar uma pasta diferente,\
     clique em Procurar."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    BrowseButton
    "<%Browse%>"

    DestinationLabel
    "Pasta de Destino"
}

SelectProgramFolder {
    Title
    "Selecione a Pasta de Programas"

    Subtitle
    "Por favor, selecione uma pasta de programa."

    Caption
    "A Instalação adicionará os ícones do programa Pasta de Programas listada abaixo. \
     Você poderá digitar um novo nome de pasta or selecionar uma das pastas da lista. \
     Clique em Próximo para continuar."

    Message
    ""

    ProgramFolderLabel
    "Pasta de Programas:"

    FolderListLabel
    "Pastas Existentes:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    AllUsersCheckbutton
    "Criar uma pasta de programa para todos os usuários"
}

SetupComplete {
    Caption
    "Assistente InstallJammer Concluído"

    Message
    "O Assistente InstallJammer instalou com sucesso o <%AppName%>. \
     Clique em Concluir para sair do assistente."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SetupType {
    Title
    "Tipo de Instalação"

    Subtitle
    "Seleciona o tipo de instalação que melhor de adapta às suas necessidades."

    Caption
    "Clique no tipo de Instalação de sua preferência."

    Message
    ""

    DescriptionLabel
    "Descrição"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

StartCopyingFiles {
    Title
    "Iniciar Cópia de Arquivos"

    Subtitle
    "Reveja as configurações antes de copiar os arquivos"

    Caption
    "A Instalação tem bastante informação para iniciar a cópia dos arquivos do programa.  Se\
     você deseja revisar or mudar qualquer configuração, clique em Voltar.  Se você está\
     satisfeito com as configurações, clique em Próximo para iniciar a cópia dos arquivos."

    Message
    ""

    Text
    "Diretório de Instalação:\n\t<%InstallDir%>\n\nTipo de Instalação:\n\t<%InstallType%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Uninstall {
    Title
    "Desinstalando"

    Subtitle
    "Desinstalando <%AppName%>"

    Caption
    "<%GroupBeingUninstalledText%>"

    Message
    ""

    FileValue
    "<%Status%>"

    ProgressValue
    "<%UninstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallComplete {
    Caption
    "Desinstalação Concluída"

    Message
    "<%AppName%> foi removido do seu sistema."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallDetails {
    Title
    "Detalhes de Desinstalação"

    Subtitle
    "Erros ocurreram durante a desinstalação"

    Caption
    "Os seguintes error ocorreram durante a desinstalação:"

    Message
    ""

    Text
    "<%Errors%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


UserInformation {
    Title
    "Informações do Proprietário"

    Subtitle
    "Por favor, digite as tuas informações."

    Caption
    "Por favor, digite seu nome e o nome da empresa onde você trabalha."

    Message
    ""

    UserNameLabel
    "Nome do Usuário:"

    CompanyLabel
    "Empresa:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


Welcome {
    Caption
    "Bem vindo ao Assistente InstallJammer para o <%AppName%>"

    Message
    "Será instalado <%AppName%> version <%Version%> em seu computador. \
    \n\nÉ recomendado que você feche todos os outros programas antes de continuar. \n\n
    Clique em Próximo para continuar ou em Cancelar para sair da Instalação."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}
