# options: -encoding utf-8

ChooseComponents {
    Title
    "Выбор компонент для установки"

    Subtitle
    "Выберите компоненты, которые вы хотите установить."

    Caption
    "Отметьте компоненты, которые вы хотите установить, и снимите отметку\
     с тех компонент, которые вы не желаете устанавливать."

    Message
    "Для установки требуется <%SpaceRequiredText%> на жестком диске"

    DescriptionLabel
    "Описание"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CopyFiles {
    Title
    "Установка"

    Subtitle
    "Установка <%AppName%>"

    Caption
    "Идёт установка <%AppName%> на Ваш компьютер. Пожалуйста, подождите."

    Message
    ""

    FileLabel
    "<%Status%>"

    ProgressValue
    "<%InstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane1 {
    Caption
    "Здесь должна быть подпись."

    Message
    "Здесь должно быть сообщение."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane2 {
    Title
    "Заголовок"

    Subtitle
    "Подзаголовок"

    Caption
    "Подпись"

    Message
    "Сообщение"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane1 {
    Title
    "Заголовок"

    Subtitle
    "Подзаголовок"

    Caption
    "Подпись"

    Message
    "Сообщение"

    Text
    "Здесь впишите текст."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

License {
    Title
    "Лицензионное Соглашение"

    Subtitle
    "Пожалуйста, внимательно прочтите приведённое ниже лицензионное соглашение."

    Text
    "Здесь должно быть лицензионное соглашение."

    AcceptRadiobutton
    "Я принимаю положения лицензионного соглашения."

    DeclineRadiobutton
    "Я не принимаю положения лицензионного соглашения."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Readme {
    Title
    "Информация"

    Subtitle
    "Информация о <%AppName%>"

    Caption
    ""

    Message
    ""

    Text
    ""

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SelectDestination {
    Title
    "Укажите каталог назначения"

    Subtitle
    "Где нужно установить <%AppName%> ?"

    Caption
    "<%AppName%> будет установлена в указанный ниже каталог.\n\nЧтобы произвести установку\
     в этот каталог, щёлкните по <%Next%>.  Чтобы произвести установку в другой каталог, щёлкните\
     по <%Browse%>."

    Message
    ""

    BrowseText
    "Для продолжения щёлкните по <%Next%>. Для указания другого каталога щёлкните по <%Browse%>."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    BrowseButton
    "<%Browse%>"

    DestinationLabel
    "Каталог назначения"
}

SelectProgramFolder {
    Title
    "Укажите программную группу"

    Subtitle
    "Пожалуйста, выберите программную группу."

    Caption
    "Ярлыки программы будут добавлены в указанную ниже программную группу. \
     Вы можете указать другую группу, либо выбрать группу из списка существующих. \
     Для продолжения щёлкните по <%Next%>."

    Message
    ""

    ProgramFolderLabel
    "Программная группа:"

    FolderListLabel
    "Существующие программные группы:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    AllUsersCheckbutton
    "Создать программную группу для всех пользователей"
}

SetupComplete {
    Caption
    "Установка завершена"

    Message
    "Мастер InstallJammer успешно установил <%AppName%>. \
     Выберите <%Finish%>, чтобы закрыть мастер."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SetupType {
    Title
    "Тип установки"

    Subtitle
    "Выберите тип установки, который вам больше всего подходит."

    Caption
    "Щёлкните по нужному вам типу установки."

    Message
    ""

    DescriptionLabel
    "Описание"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

StartCopyingFiles {
    Title
    "Начало копирования файлов"

    Subtitle
    "Просмотр информации перед началом копирования файлов"

    Caption
    "Программа установки собрала необходимую информацию для начала копирования файлов. \
     Щёлкните по <%Back%>, чтобы проверить или заново ввести информацию для установки. \
     Чтобы начать установку, щёлкните по <%Next%>."

    Message
    ""

    Text
    "Каталог назначения:
            <%InstallDir%>

    Тип установки:
            <%InstallType%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Uninstall {
    Title
    "Деинсталляция"

    Subtitle
    "Деинсталляция <%AppName%>"

    Caption
    "<%GroupBeingUninstalledText%>"

    Message
    ""

    FileValue
    "<%Status%>"

    ProgressValue
    "<%UninstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallComplete {
    Caption
    "Деинсталляция завершена"

    Message
    "<%AppName%> удалена из вашей системы."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallDetails {
    Title
    "Информация о деинсталляции"

    Subtitle
    "В процессе удаления произошли ошибки"

    Caption
    "В процессе деинсталляции произошли следующие ошибки:"

    Message
    ""

    Text
    "<%Errors%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


UserInformation {
    Title
    "Информация о пользователе"

    Subtitle
    "Пожалуйста, введите ваши данные."

    Caption
    "Пожалуйста, введите ваше имя и название компании, в которой вы работаете."

    Message
    ""

    UserNameLabel
    "Имя пользователя:"

    CompanyLabel
    "Компания:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


Welcome {
    Caption
    "Вас приветствует мастер установки InstallJammer для <%AppName%>"

    Message
    "Мастер InstallJammer установит <%AppName%> <%Version%> на вашем компьютере. \
    \n\nПеред началом установки рекомендуется закрыть все другие работающие\
    программы.\n\nЧтобы продолжить, выберите <%Next%>, или выберите <%Cancel%> для выхода."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

InstallPassword {
    Title
    "Пароль установки"

    Subtitle
    "Для продолжения установки необходимо указать пароль."

    Caption
    "Пожалуйста, введите пароль."

    Message
    ""

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}
