#!/bin/sh

port=gnome-doc-utils

# scrolls
SCROLLS="`pkginfo -l $port | grep usr/share/omf/.*\.omf$`"

for SCROLL in $SCROLLS
do
	scrollkeeper-install -q -p /var/lib/scrollkeeper /$SCROLL > /dev/null
done

# End of file
