#!/bin/bash

cross_prefix=/opt/cross/x-tools/x86_64-thinstation-linux-gnu
$cross_prefix/bin/x86_64-thinstation-linux-gnu-ranlib $cross_prefix/x86_64-thinstation-linux-gnu/sysroot/usr/lib64/libc_nonshared.a
$cross_prefix/bin/x86_64-thinstation-linux-gnu-ranlib $cross_prefix/lib/gcc/x86_64-thinstation-linux-gnu/4.9.0/libgcc.a

ln -sf $cross_prefix/x86_64-thinstation-linux-gnu/sysroot/lib /lib64
ln -sf $cross_prefix/x86_64-thinstation-linux-gnu/sysroot/usr/lib /usr/lib64


