#!/bin/bash

cross_prefix=/opt/cross/x-tools/x86_64-thinstation-linux-gnu

ln -sf $cross_prefix/x86_64-thinstation-linux-gnu/sysroot/lib /lib64
ln -sf $cross_prefix/x86_64-thinstation-linux-gnu/sysroot/usr/lib /usr/lib64


