#!/bin/sh
#
# /etc/rc.d/nfs: start/stop nfs daemons needed by nfs client and server
#

PIPEFS=/var/lib/nfs/rpc_pipefs

case $1 in
start)
	/bin/mount -t rpc_pipefs rpc_pipefs $PIPEFS
	/usr/sbin/sm-notify
	/etc/rc.d/rpc.idmapd start
	/etc/rc.d/rpc.statd start
	;;
stop)
	/etc/rc.d/rpc.statd stop
	/etc/rc.d/rpc.idmapd stop
	/bin/umount $PIPEFS
	;;
restart)
	$0 stop
	$0 start
	;;
status)
	/etc/rc.d/rpc.idmapd status
	/etc/rc.d/rpc.statd status
	;;
*)
	echo "usage: $0 [start|stop|restart|status]"
	;;
esac

# End of file
