## $Id$
##
## BEGIN LICENSE BLOCK
##
## Copyright (C) 2002  Damon Courtney
## 
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## version 2 as published by the Free Software Foundation.
## 
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License version 2 for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the
##     Free Software Foundation, Inc.
##     51 Franklin Street, Fifth Floor
##     Boston, MA  02110-1301, USA.
##
## END LICENSE BLOCK

Action PopulateSetupTypes

proc ::InstallJammer::actions::PopulateSetupTypes { obj } {
    global conf
    global info

    set step [$obj parent]

    set text    [$step widget get DescriptionText]
    set listbox [$step widget get SetupTypeListBox]

    if {[lsearch -exact $conf(SetupTypeTrees) $listbox] < 0} {
        lappend conf(SetupTypeTrees) $listbox
    }
    
    $listbox clear

    foreach id [SetupTypes children] {
        if {![$id active] || ![$id get ShowSetupType]} { continue }

        set text [::InstallAPI::GetDisplayText -object $id]
        $listbox insert end $id -text $text -data [$id name]
        if {[$id name] eq $info(InstallType)} {
            ::InstallJammer::SelectSetupType $id
        }
    }

    bind $listbox <<ListboxSelect>> {
        ::InstallJammer::SelectSetupType [%W selection get]
    }
}
