#!/bin/bash
trap "exit 1" SIGINT SIGHUP SIGTERM

export TSVER=5.6
export TSWRKNG=/ts/build
export TSPKGROOT=ts/build/packages
export TSCOMPROOT=ts/components
export REPORT_ARCH=i686
export LANG=C
export LANGUAGE=C
export LC_ALL=C
PATH=$PATH:/ts/bin:/sbin:/bin:/usr/sbin
export PATH
export PAGER=most
if [ -n "$chuser" ]; then
	export HOME=/home/$chuser
else
	export HOME=/root
fi
if [ -e /opt/jre/bin/java ]; then
	PATH=$PATH:/opt/jre/bin
fi
if [ -e /opt/meld/bin/meld ]; then
	PATH=$PATH:/opt/meld/bin
fi
if [ -e /dostage2 ] ; then
	/ts/bin/install_chroot
fi
if [ ! -e /root/.nanorc ] ;
	then cp -f /ts/.nanorc /root/.
fi

cp -af /ts/etc/* /etc/.

if [ -e /dostage3 ] ; then
	/ts/bin/install_chroot
	exit
fi

if [ -e /dostage4 ]; then
        /ts/bin/install_chroot
	touch installed
	exit
fi

if [ ! -e /ts/etc/READ ] && [ -z "$build" ] && [ -z "$exec_cmd" ] && [ -z "$clean" ] ; then
	ronn --roff -m /README.md
fi

if [ "$build" == "true" ] ; then
	cd /build
	./build $build_opts
	status=$?
	exit $status
elif [ -n "$exec_cmd" ]; then
	$exec_cmd
	status=$?
	exit $status
elif [ "$clean" == "true" ] ; then
	clean_chroot
	exit 0
else
	echo -e "\nDevelopment Environment Active. Type 'exit' to leave when done."
	/bin/bash --rcfile /ts/etc/profile
fi
