#!/bin/bash
trap "exit 1" SIGINT SIGHUP SIGTERM

export TSVER=6.2
export TSWRKNG=/ts/build
export TSPKGROOT=ts/build/packages
export TSCOMPROOT=ts/components
export LANG=C
export LANGUAGE=C
export LC_ALL=C
PATH=/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/root/bin:/ts/bin
export PATH
export PAGER=most
#export XZ_OPT="--threads=0"
export MACHTYPE=x86_64-pc-linux-gnu
if [ -n "$chuser" ]; then
	export HOME=/home/$chuser
else
	export HOME=/root
fi
if [ -e /usr/lib/java/openjdk8 ]; then
	PATH=$PATH:/usr/lib/java/openjdk8/bin
	export JAVA_HOME=/usr/lib/java/openjdk8
elif [ -e /opt/jre/bin/java ]; then
	PATH=$PATH:/opt/jre/bin
	export JAVA_HOME=/opt/jre
elif [ -e  /usr/lib/jdk/bin/java ]; then
	PATH=$PATH:/usr/lib/jdk/bin
	export JAVA_HOME=/usr/lib/jdk
elif [ -e /opt/jdk/bin/java ]; then
	PATH=$PATH:/opt/jdk/bin
	export JAVA_HOME=/opt/jdk
fi
if [ -e /opt/meld/bin/meld ]; then
	PATH=$PATH:/opt/meld/bin
fi
if [ -e /dostage2 ] ; then
	/ts/bin/install_chroot
fi

cp -af /ts/etc/* /etc/.
if [ -n "$XTRWRKNG" ]; then
	for i in $XTRWRKNG; do
		cat $XTRWRKNG/ports/prt-get.conf >> /etc/prt-get.conf
	done
fi

if [ -e /dostage3 ] ; then
	/ts/bin/install_chroot
	exit
fi

if [ -e /dostage4 ]; then
        /ts/bin/install_chroot
	touch installed
	exit
fi

if [ ! -e /ts/etc/READ ] && [ -z "$build" ] && [ -z "$exec_cmd" ] && [ -z "$clean" ] ; then
	ronn --roff -m /README.md
fi

#if [ ! -e /etc/support.love ] && [ -z "$clean" ]; then
#        /ts/bin/donate
#        loved=false
#        while ! $loved; do
#                echo "Type 'I love ThinStation!' to show your support"
#                read inclination
#                case $inclination in
#                        'I love ThinStation!') loved=true;;
#                        'I love ThinStation for real!') loved=true; touch /etc/support.love;;
#                        *) continue;;
#                esac
#        done
#fi

if [ "$build" == "true" ] ; then
	cd /build
	./build $build_opts
	status=$?
	exit $status
elif [ -n "$exec_cmd" ]; then
	$exec_cmd
	status=$?
	exit $status
elif [ "$clean" == "true" ] ; then
	clean_chroot
	exit 0
else
	echo -e "\nDevelopment Environment Active. Type 'exit' to leave when done."
	/bin/bash --rcfile /ts/etc/profile
fi
