#!/bin/sh
#
# /etc/rc.d/cifs: mount/umount cifs filesystems
#

case $1 in
start)
        /bin/mount -a -t cifs
        ;;
stop)
        /bin/umount -a -t cifs 
        ;;
restart)
        $0 stop
        sleep 2
        $0 start
        ;;
*)
        echo "usage: $0 [start|stop|restart]"
        ;;
esac

# End of file
