#!/bin/bash
# Fastboot by Donald A. Cupp Jr. don cupp jr at yahoo dot com
LANG=C
INITDIR=$1
HARDLINK=$3
FB_COMP_EXTRA=$4
echo FASTBOOT=$2 >> etc/thinstation.env
if [ "$2" == "true" ] ; then
	mv bin lib/.
	mv sbin lib/.
	ln -sf /lib/bin bin
	ln -sf /lib/sbin sbin
	mkdir lib/etc
	mkdir -p fastboot/bin
	mkdir -p fastboot/sbin
	for i in opt jre ; do
		if [ -e $i ]; then
			mv $i lib/.
			ln -sf /lib/$i $i
		fi
	done
	for i in `cat ../fastboot/etc-ro` ; do
		if [ -e etc/$i ]; then
			mv etc/$i lib/etc/.
			ln -sf /lib/etc/$i etc/$i
		fi
	done
	for i in `cat ../fastboot/lib-rw` ; do
		if [ -e lib/$i ]; then
			mv lib/$i var/.
			ln -sf /var/$i lib/$i
		fi
	done
	for i in `ls --color=never usr |grep -Ewvf ../fastboot/usr-rw` ;do
		mv usr/$i lib/.
		ln -sf /lib/$i usr/$i
	done
	for i in `cat ../fastboot/lib-boot` ; do
		if [ -e lib/$i ]; then
			mv lib/$i fastboot/.
			ln -sf /fastboot/$i lib/$i
		fi
	done
	for i in `cat ../fastboot/bin-boot` ; do
		if [ -e lib/bin/$i ]; then
			mv lib/bin/$i fastboot/bin/.
			ln -sf /fastboot/bin/$i lib/bin/$i
		fi
		if [ -e lib/sbin/$i ]; then
			mv lib/sbin/$i fastboot/sbin/.
			ln -sf /fastboot/sbin/$i lib/sbin/$i
		fi
	done
	echo -e "\tMaking lib.squash"
	timestamp="`date +%Y%m%d`0000"
	for file in `find lib`; do
		touch -c -h -t $timestamp lib/$file
	done
	if [ "$HARDLINK" == "true" ]; then
		hardlink -t -m lib
	fi
	mksquashfs lib ../$INITDIR/lib.squash -always-use-fragments -no-recovery -all-root -no-xattrs -noappend $FB_COMP_EXTRA
	for i in `ls --color=never lib/ |grep -Ewvf ../fastboot/lib-boot |grep -Ewv 'bin|sbin'` ; do
		if [ ! -z "$i" ] ; then
			rm -rf lib/$i
		fi
	done
	for i in `ls --color=never lib/bin/ |grep -Ewvf ../fastboot/bin-boot` ; do
		if [ ! -z "$i" ]; then
			rm  -rf lib/bin/$i
		fi
	done
	for i in `ls --color=never lib/sbin/ |grep -Ewvf ../fastboot/bin-boot` ; do
		if [ ! -z "$i" ]; then
			rm  -rf lib/sbin/$i
		fi
	done
	cd ..
	echo -e "\tRe-Linking BusyBox\n"
	chroot ./tmp-tree /bin/busybox --install -s
	cd tmp-tree
fi
if [ "$2" == "lotsofmem" ]; then
	mkdir -p ../fastboot-tmp/bin
	mkdir -p ../fastboot-tmp/sbin
	mkdir -p ../fastboot-tmp/lib
	mkdir -p ../fastboot-tmp/etc
	mkdir -p ../fastboot-tmp/usr
	for i in opt jre ; do
		if [ -e $i ] ; then
			mv $i ../fastboot-tmp/.
		fi
	done
	for i in `ls --color=never usr |grep -Ewvf ../fastboot/usr-rw` ; do
		mv usr/$i ../fastboot-tmp/usr/.
	done
	for i in `cat ../fastboot/etc-ro` ; do
		if [ -e etc/$i ]; then
			mv etc/$i ../fastboot-tmp/etc/.
		fi
	done
	for i in `ls --color=never lib/ |grep -Ewvf ../fastboot/lib-boot |grep -Ev 'libgmp|libattr|libacl|libz|libpcre|libidn'` ; do
		if [ ! -z "$i" ] ; then
			mv lib/$i ../fastboot-tmp/lib/.
		fi
	done
	for i in `ls --color=never bin/ |grep -Ewvf ../fastboot/bin-boot |grep -Ev '^wget$|^tftp$|^expr$|^wc$|^cut$|^cat$|^sed$|^cp$|^mv$|^readlink$|^grep$|^ifconfig$'` ; do
		if [ ! -z "$i" ] && [ "`readlink bin/$i`" != "/bin/busybox" ]; then
			mv bin/$i ../fastboot-tmp/bin/.
		fi
	done
	for i in `ls --color=never sbin/ |grep -Ewvf ../fastboot/bin-boot |grep -Ev '^wget$|^tftp$|^expr$|^wc$|^cut$|^cat$|^sed$|^cp$|^mv$|^readlink$|^grep$|^ifconfig$'` ; do
		if [ ! -z "$i" ] && [ "`readlink sbin/$i`" != "/bin/busybox" ]; then
			mv sbin/$i ../fastboot-tmp/sbin/.
		fi
	done
	cp --remove-destination /bin/cp bin/.
	cp --remove-destination /bin/mv bin/.
	cp --remove-destination /lib/libacl.so.1 lib/.
	cp --remove-destination /lib/libattr.so.1 lib/.
	if [ "$HARDLINK" == "true" ]; then
		hardlink -t -m ../fastboot-tmp
	fi
	echo -e "\tMaking lib.squash"
	mksquashfs ../fastboot-tmp/. ../$INITDIR/lib.squash -always-use-fragments -no-recovery -all-root -no-xattrs -noappend $FB_COMP_EXTRA
	cp `which unsquashfs` bin/.
	cp /usr/lib/liblzma.so.5 lib/.
fi
cd ..
chmod 755 $INITDIR/lib.squash
cd tmp-tree
