#!/bin/sh
#
# /etc/rc.d/apache: start/stop/restart apache HTTP server
#

SSD=/sbin/start-stop-daemon
PROG=/usr/sbin/httpd
PID=/var/run/apache/httpd.pid
OPTS="-k start"
KEY=/etc/apache/server.key
CRT=/etc/apache/server.crt

case $1 in
start)
	if [ ! -s $KEY -o ! -s $CRT ]; then
		/usr/bin/mksslcert $KEY $CRT
	fi
	$SSD --start --pidfile $PID --exec $PROG -- $OPTS
	;;
stop)
	$SSD --stop --retry 10 --pidfile $PID
	;;
restart)
	$0 stop
	$0 start
	;;
status)
	$SSD --status --pidfile $PID
	case $? in
	0) echo "$PROG is running with pid $(cat $PID)" ;;
	1) echo "$PROG is not running but the pid file $PID exists" ;;
	3) echo "$PROG is not running" ;;
	4) echo "Unable to determine the program status" ;;
	esac
	;;
*)
	echo "usage: $0 [start|stop|restart|status]"
	;;
esac

# End of file
