#!/bin/sh

getent group pulse || /usr/sbin/groupadd -g 112 pulse
getent group pulse-access || /usr/sbin/groupadd -g 113 pulse-access
getent passwd pulse || /usr/sbin/useradd -g pulse -u 112 -d /var/run/pulse -s /sbin/nologin -c "Pulseaudio User" pulse
/usr/bin/passwd -l pulse

