# options: -encoding utf-8

Background {
    Title
    "Instalace programu <%AppName%>"

    Text
    "<%AppName%>"
}

ChooseComponents {
    Title
    "Vlastní instalace"

    Caption
    "Zvolte součásti, které chcete nainstalovat, a zrušte vybrání součástí,\
     které nechcete nainstalovat."

    ComponentLabel
    "Součásti"

    DescriptionLabel
    "Popis"

    SpaceRequiredLabel
    "Vyžadované místo: <%SpaceRequiredText%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CopyFiles {
    Title
    "Kopírování souborů"

    Caption
    "<%GroupBeingInstalledText%>"

    Message
    "<%Status%>"

    ProgressValue
    "<%InstallPercentComplete%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane1 {
    Title
    "Instalace programu <%AppName%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


CustomTextPane1 {
    Title
    "Nadpis"

    Caption
    "Titulek"

    Message
    "Zpráva"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane2 {
    Title
    "Instalace programu <%AppName%>"

    Caption
    "Titulek"

    Text
    "Zde bude text."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane3 {
    Title
    "Nadpis"

    Caption
    "Titulek"

    Message
    "Zpráva"

    Text
    "Zde bude text."

    NextButton
    "<%Yes%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%No%>"
}

License {
    Title
    "Licenční ujednání"

    Caption
    "Prosím přečtěte si následující licenční ujednání. Stiskněte klávesu PAGE DOWN\
     pro zobrazení zbytku ujednání."

    Message
    "Přijímáte podmínky předchozího licenčního ujednání? Pokud zvolíte\
     Ne, instalátor se ukončí. K instalaci programu <%AppName%> musíte\
     přijmout toto ujednání."

    Text
    "Sem vložte své licenční ujednání."

    AcceptCheck
    "Přijímám podmínky licenčního ujednání."

    NextButton
    "Ano"

    BackButton
    "< <%Back%>"

    CancelButton
    "Ne"
}

Readme {
    Title
    "Informace ČtiMě"

    Text
    "Sem vložte vaše informace čtimě."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SelectDestination {
    Title
    "Zvolte cílové umístění"

    Caption
    "Program <%AppName%> bude nainstalován do následující složky.\n\nK instalaci\
     do této složky stiskněte Vpřed. K instalaci do jiné složky stiskněte\
     Procházet a zvolte jinou složku.\n\nStisknutím Zrušit ukončíte instalaci\
     programu <%AppName%>."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    BrowseButton
    "<%Browse%>"

    DestinationLabel
    "Cílová složka"
}

SelectProgramFolder {
    Title
    "Zvolte složku programu"

    Caption
    "Instalátor přidá ikony programu do složky programu uvedené níže.\
     Můžete vepsat odlišný název složky nebo ji vybrat ze seznamu existujících složek.\
     K pokračování stiskněte Vpřed."

    ProgramFolderLabel
    "Složka programu:"

    FolderListLabel
    "Existující složky:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    AllUsersCheckbutton
    "Vytvořit složku programu pro všechny uživatele"
}

Setup {
    Title
    "Instalace"

    Caption
    "Instalátor připravuje průvodce InstallJammer, který vás provede zbytkem\
     procesu instalace. Prosím čekejte."
}

SetupComplete {
    Title
    "Instalace dokončena"

    Caption
    "Instalátor dokončil instalaci programu <%AppName%> na váš počítač."

    Text
    "Stiskněte Dokončit pro dokončení instalace."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SetupType {
    Title
    "Typ instalace"

    Caption
    "Zvolte typ instalace, který vám nejlépe vyhovuje, a stiskněte Vpřed."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

StartCopyingFiles {
    Title
    "Spustit kopírování souborů"

    Caption
     "Instalátor má dostatek informací pro spustění kopírování souborů programu. Pokud\
     chcete zkontrolovat nebo změnit jakékoliv nastavení, stiskněte Zpět. Pokud jste\
     spokojeni s nastavením, stiskněte Vpřed pro spuštění kopírování souborů.\
     \n\nAktuální nastavení:"

    Text
    "Instalační složka:\n\
     \t<%InstallDir%>

    Typ instalace:\n\
    \t<%InstallType%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Uninstall {
    Title
    "Odinstalace programu <%AppName%>"

    Caption
    "<%GroupBeingUninstalledText%>"

    Message
    "<%Status%>"

    ProgressValue
    "<%UninstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallComplete {
    Title
    "Odinstalace dokončena"

    Caption
    "Odinstalace úspěšně dokončena."

    FinishButton
    "<%Finish%>"
}

UninstallDetails {
    Title
    "Podrobnosti odinstalace"

    Caption
    "Následující chyby nastaly během odstraňování:"

    Errors
    "<%Errors%>"

    FinishButton
    "<%Finish%>"
}


UserInformation {
    Title
    "Uživatelské informace"

    Caption
    "Vepište níže své jméno a společnost, pro kterou pracujete."

    NameLabel
    "Jméno:"

    CompanyLabel
    "Společnost:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Welcome {
    Title
    "Uvítací obrazovka"

    Caption
    "Vítejte v instalátoru programu <%AppName%>. Tento program nainstaluje\
     aplikaci <%AppName%> na váš počítač."

    Message
    "Je důrazně doporučeno ukončit všechny programy Windows, které máte\
     spuštěné. Stiskněte Vpřed k pokračování v instalaci.\n\nVAROVÁNÍ: \
     Tento program je chráněn autorským právem a mezinárodními\
     dohodami.\n\nNepovolená reprodukce nebo šíření tohoto programu, \
     nebo jeho libovolné části, může vyústit ve vážné občanské a kriminální postihy\
     a bude stíháno v maximálním možném právním rozsahu."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}
