Background {
    Title
    "<%AppName%> Setup"

    Text
    "<%AppName%>"
}

ChooseComponents {
    Title
    "Benutzerdefinierte Einstellungen"

    Caption
    "Wählen Sie die zu installierenden Komponenten aus und deselektieren Sie\
    die Komponenten, die Sie nicht installieren möchten."

    ComponentLabel
    "Komponenten"

    DescriptionLabel
    "Beschreibung"

    SpaceRequiredLabel
    "<%SpaceRequiredText%> an Plattenplatz benötigt"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CopyFiles {
    Title
    "Kopiere Dateien"

    Caption
    "<%GroupBeingInstalledText%>"

    Message
    "<%Status%>"

    ProgressValue
    "<%InstallPercentComplete%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane1 {
    Title
    "<%AppName%> Setup"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


CustomTextPane1 {
    Title
    "Titel"

    Caption
    "Überschrift"

    Message
    "Meldung"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane2 {
    Title
    "<%AppName%> Setup"

    Caption
    "Überschrift"

    Text
    "Text kommt hier hin."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane3 {
    Title
    "Title"

    Caption
    "Überschrift"

    Message
    "Meldung"

    Text
    "Text kommt hier hin."

    NextButton
    "<%Yes%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%No%>"
}

License {
    Title
    "Lizenzbestimmungen"

    Caption
    "Bitte lesen Sie die folgenden Lizenzbestimmungen.  Press the PAGE DOWN key\
     to see the rest of the agreement."

    Message
    "Akzeptieren Sie die vorangegangenen Lizenzbestimmungen? Wenn Sie Nein\
    wählen, wird die Installation beendet. Um <%AppName%> zu installieren,\
    müssen Sie den Lizenzbestimmungen zustimmen."

    Text
    "Hier kommen Ihre Lizenzbestimmungen hin."

    AcceptCheck
    "Ich akzeptiere die Lizenzbestimmungen."

    NextButton
    "Ja"

    BackButton
    "< <%Back%>"

    CancelButton
    "Nein"
}

Readme {
    Title
    "Liesmich Informationen"

    Text
    "Hier kommen Ihre Liesmich Informationen hin."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SelectDestination {
    Title
    "Auswahl Installationsziel"

    Caption
    "Setup wird <%AppName%> in das folgende Verzeichnis installieren. \
    \n\nKlicken Sie auf Weiter, wenn dieses Verzeichnis verwendet werden soll. \
    \n\nUm ein anderes Verzeichnis auszuwählen, klicken Sie auf Durchsuchen\
    \n\nMöchten Sie <%AppName%> nicht installieren,\
    dann klicken Sie auf Abbrechen, um das Setup zu verlassen."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    BrowseButton
    "<%Browse%>"

    DestinationLabel
    "Zielordner"
}

SelectProgramFolder {
    Title
    "Auswahl Programmordner"

    Caption
    "Setup wird die Programmsymbole zum unten aufgeführten Programmordner\
    hinzufügen. Sie können einen neuen Ordnernamen eingeben oder einen von der\
    von der existierenden Ordnerliste auswählen. Klicken Sie auf Weiter um\
    Fortzufahren."

    ProgramFolderLabel
    "Programmordner:"

    FolderListLabel
    "Vorhandene Ordner:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    AllUsersCheckbutton
    "Erstelle Programmordner für alle Benutzer"
}

Setup {
    Title
    "Setup"

    Caption
    "Setup bereitet den InstallJammer Assistenten vor, der Sie durch den\
    Rest des Installationsvorgang führen wird. Bitte warten Sie."
}

SetupComplete {
    Title
    "Setup Vollständig"

    Caption
    "Setup hat die Installation von <%AppName%> auf Ihrem Computer beendet."

    Text
    "Klicken Sie auf Beenden, um Setup zu verlassen."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SetupType {
    Title
    "Setup Art"

    Caption
    "Klicken Sie auf die bevorzugte Art des Setup, dann auf Weiter."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

StartCopyingFiles {
    Title
    "Start Copying Files"

    Caption
    "Setup hat genug Informationen, um die Programmdateien zu kopieren. \
    Wenn Sie die Einstellungen überprüfen oder ändern möchten,\
    klicken Sie auf Zurück. Wenn Sie mit den Einstellungen zufrieden sind,\
    klicken Sie auf Weiter, um mit dem Kopieren der Dateien zu beginnen. \
    \n\nDerzeitige Einstellungen:"
    

    Text
    "Install Directory:\n\
     \t<%InstallDir%>

    Setup Type:\n\
    \t<%InstallType%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Uninstall {
    Title
    "Deinstallation <%AppName%>"

    Caption
    "<%GroupBeingUninstalledText%>"

    Message
    "<%Status%>"

    ProgressValue
    "<%UninstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallComplete {
    Title
    "Deinstallation Abgeschlossen"

    Caption
    "Deinstallation erfolgreich abgeschlossen."

    FinishButton
    "<%Finish%>"
}

UninstallDetails {
    Title
    "Deinstallation Details"

    Caption
    "Die folgenden Fehler sind beim Löschen aufgetreten:"

    Errors
    "<%Errors%>"

    FinishButton
    "<%Finish%>"
}


UserInformation {
    Title
    "Benutzer Information"

    Caption
    "Bitte geben Sie Ihren Namen und den Namen der Firma ein, für die Sie\
    arbeiten."

    NameLabel
    "Name:"

    CompanyLabel
    "Firma:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Welcome {
    Title
    "Willkommen"

    Caption
    "Willkommen zum Setup von <%AppName%>. Dieses Programm wird <%AppName%>\
    auf Ihrem Computer installieren."

    Message
    "Es wird empfohlen, das Sie alle anderen Anwendungen schließen, bevor\
    Sie fortfahren.\n\nKlicken Sie auf Weiter um Fortzufahren.\n\nWARNUNG:\
    Dies Programm ist urheberrechtlich geschützt. Nicht authorisierte\
    Vervielfältigung oder Verbreitung von diesem Programm oder Teilen dessen,\
    können zu erheblichen Strafen führen und diese werden nach maximalen\
    Möglichkeiten der geltenden Gesetze angewendet."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}
