Background {
    Title
    "<%AppName%> Setup"

    Text
    "<%AppName%>"
}

ChooseComponents {
    Title
    "Custom Setup"

    Caption
    "Select the components you want to install and deselect the components\
     you do not want to install."

    ComponentLabel
    "Components"

    DescriptionLabel
    "Description"

    SpaceRequiredLabel
    "Space Required: <%SpaceRequiredText%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CopyFiles {
    Title
    "Copying Files"

    Caption
    "<%GroupBeingInstalledText%>"

    Message
    "<%Status%>"

    ProgressValue
    "<%InstallPercentComplete%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane1 {
    Title
    "<%AppName%> Setup"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


CustomTextPane1 {
    Title
    "Title"

    Caption
    "Caption"

    Message
    "Message"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane2 {
    Title
    "<%AppName%> Setup"

    Caption
    "Caption"

    Text
    "Text goes here."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane3 {
    Title
    "Title"

    Caption
    "Caption"

    Message
    "Message"

    Text
    "Text goes here."

    NextButton
    "<%Yes%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%No%>"
}

License {
    Title
    "License Agreement"

    Caption
    "Please read the following License Agreement.  Press the PAGE DOWN key\
     to see the rest of the agreement."

    Message
    "Do you accept all the terms of the preceding License Agreement?  If\
     you choose No, Setup will close.  To install <%AppName%>, you must\
     accept this agreement."

    Text
    "Put your license agreement here."

    AcceptCheck
    "I accept the terms of this license agreement."

    NextButton
    "Yes"

    BackButton
    "< <%Back%>"

    CancelButton
    "No"
}

Readme {
    Title
    "Readme Information"

    Text
    "Put your readme information here."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SelectDestination {
    Title
    "Select Destination Location"

    Caption
    "Setup will install <%AppName%> in the following folder.\n\nTo install\
     to this folder, click Next.\n\nTo install to a different folder, click\
     Browse and select another folder.\n\nYou can choose not to install\
     <%AppName%> by clicking Cancel to exit Setup."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    BrowseButton
    "<%Browse%>"

    DestinationLabel
    "Destination Folder"
}

SelectProgramFolder {
    Title
    "Select Program Folder"

    Caption
    "Setup will add the program icons to the Program Folder listed below. \
     You may type a new folder name or select from the existing folders list. \
     Click Next to continue."

    ProgramFolderLabel
    "Program Folder:"

    FolderListLabel
    "Exising Folders:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    AllUsersCheckbutton
    "Create program folder for all users"
}

Setup {
    Title
    "Setup"

    Caption
    "Setup is preparing the InstallJammer Wizard which will guide you through\
     the rest of the setup process.  Please wait."
}

SetupComplete {
    Title
    "Setup Complete"

    Caption
    "Setup has finished installing <%AppName%> on your computer."

    Text
    "Click Finish to complete Setup."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SetupType {
    Title
    "Setup Type"

    Caption
    "Click the type of Setup you prefer, then click Next."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

StartCopyingFiles {
    Title
    "Start Copying Files"

    Caption
    "Setup has enough information to start copying the program files.  If\
     you want to review or change any settings, click Back.  If you are\
     satisfied with the settings, click Next to begin copying files. \
     \n\nCurrent Settings:"

    Text
    "Install Directory:\n\
     \t<%InstallDir%>

    Setup Type:\n\
    \t<%InstallType%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Uninstall {
    Title
    "Uninstall <%AppName%>"

    Caption
    "<%GroupBeingUninstalledText%>"

    Message
    "<%Status%>"

    ProgressValue
    "<%UninstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallComplete {
    Title
    "Uninstall Complete"

    Caption
    "Uninstall Completes Successfully."

    FinishButton
    "<%Finish%>"
}

UninstallDetails {
    Title
    "Uninstall Details"

    Caption
    "The following errors occurred during uninstall:"

    Errors
    "<%Errors%>"

    FinishButton
    "<%Finish%>"
}


UserInformation {
    Title
    "User Information"

    Caption
    "Type your name and the company you work for below."

    NameLabel
    "Name:"

    CompanyLabel
    "Company:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Welcome {
    Title
    "Welcome Screen"

    Caption
    "Welcome to the <%AppName%> Setup program.  This program will install\
     <%AppName%> on your computer."

    Message
    "It is strongly recommended that you exit all Windows programs you have\
     running.  Click Next to continue with the Setup program.\n\nWARNING:\
     This program is protected by copyright law and international\
     treaties.\n\nUnauthorized reproduction or distribution of this program,\
     or any portion of it, may result in severe civil and criminal penalties,\
     and will be prosecuted to the maximum extent possible under law."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}
