Background {
    Title
    "Instalación de <%AppName%>"

    Text
    "<%AppName%>"
}

ChooseComponents {
    Title
    "Instalación Personalizada"

    Caption
    "Seleccione los componentes que desea instalar y elimine aquéllos\
    que no desea que sean instalados."

    ComponentLabel
    "Componentes"

    DescriptionLabel
    "Descripción"

    SpaceRequiredLabel
    "Espacio Requerido: <%SpaceRequiredText%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CopyFiles {
    Title
    "Copiando Archivos"

    Caption
    "<%GroupBeingInstalledText%>"

    Message
    "<%Status%>"

    ProgressValue
    "<%InstallPercentComplete%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane1 {
    Title
    "Instalación de <%AppName%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


CustomTextPane1 {
    Title
    "Título"

    Caption
    "Leyenda"

    Message
    "Mensaje"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane2 {
    Title
    "Instalación de <%AppName%>"

    Caption
    "Leyenda"

    Text
    "Texto aquí."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane3 {
    Title
    "Título"

    Caption
    "Leyenda"

    Message
    "Mensaje"

    Text
    "Texto aquí."

    NextButton
    "<%Yes%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%No%>"
}

License {
    Title
    "Acuerdo de Licencia"

    Caption
    "Por favor lea el siguiente Acuerdo de Licencia. Presione Av.Pag\
    para ver el resto del acuerdo."

    Message
    "¿Acepta los terminos del Acuerdo de Licencia anterior?\
    Si escoge No, la instalación se cerrara. Para instalar <%AppName%>,\
    debe aceptar este acuerdo."

    Text
    "Ponga aquí su Acuerdo de Licencia."

    AcceptCheck
    "Acepto los términos de este Acuerdo de Licencia."

    NextButton
    "Sí"

    BackButton
    "< <%Back%>"

    CancelButton
    "No"
}

Readme {
    Title
    "Léame"

    Text
    "Ponga aqui su Léame."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SelectDestination {
    Title
    "Seleccione carpeta destino"

    Caption
    "Se instalará <%AppName%> en la siguiente carpeta.\n\nPara instalar en\
    esta carpeta, pulse Siguiente.\n\nPara instalar en una carpeta diferente,\
    pulse Examinar y seleccione otra carpeta.\n\nPuede escoger no instalar\
    <%AppName%> pulsando Cancelar para salir de la instalación."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    BrowseButton
    "<%Browse%>"

    DestinationLabel
    "Carpeta Destino"
}

SelectProgramFolder {
    Title
    "Seleccione Grupo de Programas"

    Caption
    "Se instalarán iconos en el Grupo de Programas siguiente. \
    Puede escribir un nuevo nombre de grupo o seleccionarlo\
    de la lista de grupos existentes. \
    Pulse Siguiente para continuar."

    ProgramFolderLabel
    "Grupo de Programas:"

    FolderListLabel
    "Grupos Existentes:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    AllUsersCheckbutton
    "Crear grupo de programas para todos los usuarios"
}

Setup {
    Title
    "Instalación"

    Caption
    "El programa de instalación está preparando el Wizard InstallJammer, que\
    le guiara a través del proceso de instalación. Por favor espere."
}

SetupComplete {
    Title
    "Instalación Completa"

    Caption
    "Se ha finalizado la instalación de <%AppName%> en su equipo."

    Text
    "Pulse Finalizar para completar la instalación."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SetupType {
    Title
    "Tipo de Instalación"

    Caption
    "Seleccione el tipo de instalación que prefiere, y pulse Siguiente."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

StartCopyingFiles {
    Title
    "Comenzar a Copiar Archivos"

    Caption
    "Se ha recopilado la información necesaria para comenzar a copiar los\
    archivos del programa. Si desea revisar o cambiar la configuración,\
    pulse Atrás. Si esta conforme con la configuración, pulse Siguiente para\
    comenzar a copiar los archivos.
    \n\nConfiguración actual:"

    Text
    "Directorio de Instalación:\n\
     \t<%InstallDir%>

    Tipo de Instalación:\n\
    \t<%InstallType%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Uninstall {
    Title
    "Desinstalación de <%AppName%>"

    Caption
    "<%GroupBeingUninstalledText%>"

    Message
    "<%Status%>"

    ProgressValue
    "<%UninstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallComplete {
    Title
    "Desinstalación Completa"

    Caption
    "La Desinstalación se completó con exito."

    FinishButton
    "<%Finish%>"
}

UninstallDetails {
    Title
    "Detalles de la Desinstalación"

    Caption
    "Ocurrieron los siguientes errores durante el proceso de desinstalación:"

    Errors
    "<%Errors%>"

    FinishButton
    "<%Finish%>"
}


UserInformation {
    Title
    "Información de Usuario"

    Caption
    "Escriba su nombre y empresa a continuación."

    NameLabel
    "Nombre:"

    CompanyLabel
    "Empresa:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Welcome {
    Title
    "Pantalla de Bievenida"

    Caption
    "Bienvenido al programa de instalación de <%AppName%>. Este programa instalará\
     <%AppName%> en su equipo."

    Message
    "Se recomienda salir de todos los programas Windows que este ejecutando. \
    Pulse Siguiente para continuar con el programa de instalación.\n\nADVERTENCIA:\
    Este programa esta protegido con copyright y los acuerdos internacionales.\n\n
    La reproducción o distribución no autorizada de este programa, o parte del mismo,\
    puede acarrear penas civiles y criminales, y será perseguida por la ley."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}
