Background {
    Title
    "Installation <%AppName%>"

    Text
    "<%AppName%>"
}

ChooseComponents {
    Title
    "Installation personnalisée"

    Caption
    "Sélectionner les composants à installer et déselectionner les composants à ne pas installer."

    ComponentLabel
    "Composants"

    DescriptionLabel
    "Description"

    SpaceRequiredLabel
    "Espace requis: <%SpaceRequiredText%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CopyFiles {
    Title
    "Copie des fichiers"

    Caption
    "<%GroupBeingInstalledText%>"

    Message
    "<%Status%>"

    ProgressValue
    "<%InstallPercentComplete%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane1 {
    Title
    "<%AppName%> Setup"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


CustomTextPane1 {
    Title
    "Titre"

    Caption
    "Légende"

    Message
    "Message"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane2 {
    Title
    "Installation <%AppName%>"

    Caption
    "Légende"

    Text
    "Saisir le texte ici."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane3 {
    Title
    "Titre"

    Caption
    "Légende"

    Message
    "Message"

    Text
    "Saisir le texte ici."

    NextButton
    "<%Yes%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%No%>"
}

License {
    Title
    "Accord de licence"

    Caption
    "Lisez SVP l'accord de licence suivant.  Appuyez sur la touche PAGE DOWN\
     pour lire la suite de l'accord de licence."

    Message
    "Acceptez-vous tous les termes du précédent accord de licence ?  Si\
     vous choisissez Non, l'installation s'arrêtera.  Pour installer <%AppName%>, vous devez\
     accepter cet accord de licence."

    Text
    "Mettez votre accord de licence ici."

    AcceptCheck
    "J'accepte les termes de cet accord de licence."

    NextButton
    "Oui"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%No%>"
}

Readme {
    Title
    "Readme"

    Text
    "Mettez les informations de votre Readme ici."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SelectDestination {
    Title
    "Sélectionnez le répertoire d'installation"

    Caption
    "L'installation de <%AppName%> s'effectuera dans le répertoire suivant.\n\nPour installer\
     dans ce répertoire, cliquez sur le bouton SUIVANT.\n\nPour installer dans un autre répertoire, cliquez\
     sur le bouton PARCOURIR et sélectionnez un autre répertoire.\n\nVous pouvez choisir de ne pas installer\
     <%AppName%> en cliquant sur le bouton ANNULER pour sortir de l'installation."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    BrowseButton
    "<%Browse%>"

    DestinationLabel
    "Répertoire d'installation"
}

SelectProgramFolder {
    Title
    "Sélectionnez le dossier Programme"

    Caption
    "L'installation ajoutera les icônes de programme au dossier Programme affiché ci-dessous. \
     Vous pouvez saisir un nouveau nom de dossier ou en sélectionner un dans la liste des dossiers existants. \
     Cliquez sur SUIVANT pour continuer."

    ProgramFolderLabel
    "Dossier Programme :"

    FolderListLabel
    "Dossiers existants :"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    AllUsersCheckbutton
    "Créer le dossier programme pour tous les utilisateurs"
}

Setup {
    Title
    "Installation"

    Caption
    "L'installation prépare l'assistant InstallJammer qui vous guidera tout\
     au long du processus d'installation.  Patientez SVP."
}

SetupComplete {
    Title
    "Installation terminée"

    Caption
    "L'installation de <%AppName%> sur votre ordinateur est terminée."

    Text
    "Cliquez sur TERMINER pour finir l'installation."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SetupType {
    Title
    "Type d'installation"

    Caption
    "Cliquez sur le type d'installation que vous souhaitez, puis cliquez sur SUIVANT."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

StartCopyingFiles {
    Title
    "Copie des fichiers"

    Caption
    "L'installeur a maintenant assez d'informations pour commencer à copier les fichiers.  Si\
     vous voulez revoir ou modifier le paramétrage, cliquez sur PRECEDENT.  Si vous êtes\
     satisfait du paramétrage, cliquez sur suivant pour commencer à copier les fichiers. \
     \n\nParamétrage courant:"

    Text
    "Répertoire d'installation:\n\
     \t<%InstallDir%>

    Type d'installation:\n\
    \t<%InstallType%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Uninstall {
    Title
    "Désinstaller <%AppName%>"

    Caption
    "<%GroupBeingUninstalledText%>"

    Message
    "<%Status%>"

    ProgressValue
    "<%UninstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallComplete {
    Title
    "Désinstallation terminée"

    Caption
    "La désinstallation s'est bien terminée."

    FinishButton
    "<%Finish%>"
}

UninstallDetails {
    Title
    "Details de la désinstallation"

    Caption
    "Les erreurs suivantes sont apparues pendant la désinstallation:"

    Errors
    "<%Errors%>"

    FinishButton
    "<%Finish%>"
}


UserInformation {
    Title
    "Informations sur l'utilisateur"

    Caption
    "Saisissez votre nom et votre société ci-dessous."

    NameLabel
    "Nom:"

    CompanyLabel
    "Société:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Welcome {
    Title
    "Ecran d'accueil"

    Caption
    "Bienvenue dans le programme d'installation de <%AppName%>.  Ce programme installera\
     <%AppName%> sur votre ordinateur."

    Message
    "Il est fortement recommandé de fermer tous les programmes en cours d'exécution. \
     Cliquez sur SUIVANT pour continuer l'installation.\n\nATTENTION:\
     Ce programme est protégé par les lois du copyright et les traités\
     internationaux.\n\nToute reproduction interdite ou distribution de ce programme,\
     dans son intégralité ou en partie, entrainera des poursuites civils et criminelles,\
     avec l'ampleur maximale autorisée par la loi."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}
