Background {
    Title
    "<%AppName%> Telepítés"

    Text
    "<%AppName%>"
}

ChooseComponents {
    Title
    "Egyedi telepítés"

    Caption
    "Válassza ki azokat a komponenseket, amelyeket fel akar telepíteni,\
     és ne válassza ki azokat, amelyeket nem akar telepíteni."

    ComponentLabel
    "Komponensek"

    DescriptionLabel
    "Leírás"

    SpaceRequiredLabel
    "Szükséges tárterület: <%SpaceRequiredText%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CopyFiles {
    Title
    "Állományok másolása"

    Caption
    "<%GroupBeingInstalledText%>"

    Message
    "<%Status%>"

    ProgressValue
    "<%InstallPercentComplete%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane1 {
    Title
    "A fejléc jön ide."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane1 {
    Title
    "Cím"

    Caption
    "Leírás"

    Message
    "Üzenet"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane2 {
    Title
    "<%AppName%> Telepítés"

    Caption
    "Fejléc"

    Text
    "Szöveg kerül ide."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane3 {
    Title
    "Cím"

    Caption
    "Fejléc"

    Message
    "Üzenet"

    Text
    "Szöveg kerül ide."

    NextButton
    "<%Yes%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%No%>"
}

License {
    Title
    "Licensz elfogadása"

    Caption
    "Kérem olvassa el a következ\u0151 Licensz megállapodást. Nyomja le a PAGE DOWN billenty\u0171t,\
     hogy lássa a megállapodás további részét."

    Message
    "Elfogadja a fenti Licensz megállapodás minden feltételét? Ha\
     Nem-et választ, akkor a telepítés befejez\u0151dik. A <%AppName%> telepítéséhez el kell fogadnia\
     ezt a megállapodást."

    Text
    "Rakja ide a licensz megállapodását."

    AcceptCheck
    "Elfogadom ezt a licensz megállapodás feltételeit."

    NextButton
    "<%Yes%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%No%>"
}

Readme {
    Title
    "Olvassa el információk"

    Text
    "Rakja ide az olvassa el információit."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SelectDestination {
    Title
    "Válassza ki a célkönyvtárat"

    Caption
    "A telepít\u0151 a <%AppName%> programot a következ\u0151 könyvtárba telepíti.\n\n
     Ahhoz, hogy ebbe könyvtárba kerüljön kattintson a <%Next%> gombra\
     Ahhoz, hogy más könyvtárba kerüljön kattintson a <%Browse%> gombra.\n\n
	 A <%Cancel%> választásával kiléphet a <%AppName%> program telepítéséb\u0151l."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    BrowseButton
    "<%Browse%>"

    DestinationLabel
    "Célkönyvtár"
}

SelectProgramFolder {
    Title
    "Program mappa kiválasztás"

    Caption
    "A telepít\u0151 a program ikonokat a lentebb listázott Program mappához fogja hozzáadni. \
	 Megváltoztathatja az új mappa nevét, vagy kiválaszthat egy már létez\u0151t a listáról. \
     Kattintson a <%Next%> gombra a folytatáshoz."

    ProgramFolderLabel
    "Program mappa:"

    FolderListLabel
    "Létez\u0151 mappák:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    AllUsersCheckbutton
    "Létrehozza a program mappát az összes felhasználónak?"
}

Setup {
    Title
    "Telepítés"

    Caption
    "A telepít\u0151 el\u0151készíti az InstallJammer Varázslót, amely keresztülvezeti Önt a\
	 telepítés folyamatán. Kérem várjon!"
}

SetupComplete {
    Title
    "Telepítés befejez\u0151dött"

    Caption
    "A telepít\u0151 befejezte az <%AppName%> program telepítését a számítógépére."

	Text
	"Kattintson a <%Finish%> gombra a telepítés befejezéséhez."
	
    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SetupType {
    Title
    "Telepítés típusa"

    Caption
    "Válassza ki a kívánt telepítési típust, majd kattintson a <%Next%> gombra!"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

StartCopyingFiles {
    Title
    "Állományok másolásának elkezdése"

    Caption
    "A telepít\u0151nek elég információja van ahhoz, hogy a program állományait\
	elkezdje másolni. Ha meg akarja nézni vagy változtatni a beállításokat,\
	akkor kattintson a <%Back%> gombra. Ha elégedett a beállításokkal, akkor\
	kattintson a <%Next%> gombra, hogy elkezd\u0151djön a fájlok másolása. \
	\n\nJelenlegi beállítások:"

    Text
    "Telepítési könyvtár:\n\
     \t<%InstallDir%>

    Telepítés típusa:\n
     \t<%InstallType%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Uninstall {
    Title
    "<%AppName%> eltávolítása"

    Caption
    "<%GroupBeingUninstalledText%>"

    Message
    "<%Status%>"

    ProgressValue
    "<%UninstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallComplete {
    Title
    "Eltávolítás befejez\u0151dött"

    Caption
    "Az eltávolítás sikeresen befejez\u0151dött."

    FinishButton
    "<%Finish%>"
}

UninstallDetails {
    Title
    "Eltávolítás részletei"

    Caption
    "A következ\u0151 hibák léptek fel az eltávolítás alatt:"

	Errors
    "<%Errors%>"

    FinishButton
    "<%Finish%>"
}


UserInformation {
    Title
    "Felhasználói információk"

    Caption
    "Kérem írja be a nevét és a munkahelyének nevét."

    NameLabel
    "Felhasználó neve:"

    CompanyLabel
    "Cég:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


Welcome {
    Title
    "Üdvözl\u0151 képerny\u0151"

    Caption
    "Üdvözli a <%AppName%> telepít\u0151je.  Ez program a <%AppName%> programot\
     fogja telepíteni a számítógépére."

    Message
    "Er\u0151sen javasolt, hogy lépjen ki minden futó Windows programból. \
	 Kattintson a <%Next%> gombra, hogy folytassa a telepítést.\n\n\
	 FIGYELMEZTETÉS: Ezt a programot szerz\u0151i jogok és nemzetközi szerz\u0151dések\
	 védik.\n\nEzen program nem engedélyezett gyártása és forgalmazása\
	 polgári büntetést eredményezhet és a törvény teljes erejével sújt le."
	 
    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}
