Background {
    Title
    "<%AppName%> ádiegimo programa"

    Text
    "<%AppName%>"
}

ChooseComponents {
    Title
    "Pasirenkamasis ádiegimas"

    Caption
    "Paþymëkite komponentus kuriuos norite ádiegti ir atþymëkite\
     tuos kuriuos nenorite ádiegti."

    ComponentLabel
    "Komponentai"

    DescriptionLabel
    "Apraðymas"

    SpaceRequiredLabel
    "Reikalinga talpa: <%SpaceRequiredText%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CopyFiles {
    Title
    "Kopijuojami failai"

    Caption
    "<%GroupBeingInstalledText%>"

    Message
    "<%Status%>"

    ProgressValue
    "<%InstallPercentComplete%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane1 {
    Title
    "<%AppName%> diegimo programa"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


CustomTextPane1 {
    Title
    "Antraðtë"

    Caption
    "Pavadinimas"

    Message
    "Praneðimas"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane2 {
    Title
    "<%AppName%> diegimo programa"

    Caption
    "Antraðtë"

    Text
    "Èia ávedamas tekstas."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane3 {
    Title
    "Antraðtë"

    Caption
    "Pavadinimas"

    Message
    "Praneðimas"

    Text
    "Èia ávedamas tekstas."

    NextButton
    "<%Yes%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%No%>"
}

License {
    Title
    "Sutikimas su licencija"

    Caption
    "Praðom perskaityti ðá sutikimà su licencija. Spauskite PAGE DOWN klaviðà\
     tam kad perþiûrëtumëte visà susitarimà."

    Message
    "Ar jûs sutinkate su licensija? Jei pasirinksite Ne, diegimo programa\
	uþsidarys. Tam kad ádiegti <%AppName%>, jûs privalote sutikti su\
	licencija"

    Text
    "Patalpinkite èia savo licencijà."

    AcceptCheck
    "Að sutinku su licencija."

    NextButton
    "Taip"

    BackButton
    "< <%Back%>"

    CancelButton
    "Ne"
}

Readme {
    Title
    "Skaityti daugiau informacijos"

    Text
    "Patalpinkite informacija."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SelectDestination {
    Title
    "Pasirinkite paskirties vietà"

    Caption
    "Diegimo programa ádiegs <%AppName%> á ðá katalogà.\n\nTam kad instaliuoti\
     á ðá katalogà, paspauskite <%Next%>.\n\nÁdiegimui á kita katalogà,\
     paspauskite <%Browse%> ir pasirinkite kità katalogà.\n\nTam kad nutraukti\
     <%AppName%> programos diegimà spauskite <%Cancel%>."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    BrowseButton
    "<%Browse%>"

    DestinationLabel
    "Paskirties katalogas"
}

SelectProgramFolder {
    Title
    "Pasirinkite programos katalogà"

    Caption
    "Diegimo programa ákels programos ikonas á programø katalogà pavaizduotà\
     apaèioje.  Galite ávesti naujà katalogo pavadinimà arba pasirinkti ið\
     esanèiø.  Norëdami tæsti <%Next%>."

    ProgramFolderLabel
    "Programos katalogas:"

    FolderListLabel
    "Esantys katalogai:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    AllUsersCheckbutton
    "Sukurti programos katalogus visiems vartotojams"
}

Setup {
    Title
    "Diegimo programa"

    Caption
    "Diegimo programa ruoðia InstallJammer vedlá, kuris jus ves\
     per diegimo prosesà. Praðom palaukti."
}

SetupComplete {
    Title
    "Diegimas baigtas"

    Caption
    "Diegimo programa baigë diegti <%AppName%> á jûsø kompiuterá."

    Text
    "Paspauskite <%Finish%>, kad uþbaigti diegimà."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SetupType {
    Title
    "Diegimo tipas"

    Caption
    "Pasirinkite diegimo tipà, tada spauskite <%Next%>."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

StartCopyingFiles {
    Title
    "Pradedamas failø kopijavimas"

    Caption
    "Diegimo programa turi pakankamai informacijos, kad pradëti kopijuoti
     programos failus.  Jei norite perþiûrëti arba pakeisti nustatymus,\
     spauskite <%Back%>. Jei nustatymai tenkina, spauskite <%Next%>, kad\
     pradëti kopijuoti failus.\n\nDabartiniai nustatymai:"

    Text
    "Diegimo katalogas:\n\
     \t<%InstallDir%>

    Diegimo tipas:\n\
    \t<%InstallType%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Uninstall {
    Title
    "Paðalinti <%AppName%>"

    Caption
    "<%GroupBeingUninstalledText%>"

    Message
    "<%Status%>"

    ProgressValue
    "<%UninstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallComplete {
    Title
    "Programos paðalinimas baigtas"

    Caption
    "Programos paðalinimas sëkmingai atliktas."

    FinishButton
    "<%Finish%>"
}

UninstallDetails {
    Title
    "Programos paðalinimas iðsamiau"

    Caption
    "Klaidos atsitikusios per programos paðalinimà:"

    Errors
    "<%Errors%>"

    FinishButton
    "<%Finish%>"
}


UserInformation {
    Title
    "Vartotojo informacija"

    Caption
    "Áveskite savo vardà ir organizacijà kurioje dirbate."

    NameLabel
    "Vardas:"

    CompanyLabel
    "Organizacija:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Welcome {
    Title
    "Pasveikinimo ekranas"

    Caption
    "Sveiki atvyke á <%AppName%> diegimo programà. Ði programa ádiegs\
     <%AppName%> á jûsø kompiuterá."

    Message
    "Pabrëþtinai patartina iðeiti ið visø Windows programø kurias esate\
     pasileidæ. Spauskite <%Next%> tam, kad tæsti diegimà.\n\nDËMESIO:\
     Ði programa yra saugoma autoriniø teisiø ir tarptautiniais ástatymais.\
     \n\nNelegalus ðios programos kopijavimas arba platinimas, baudþiamas\
     pagal civilinës ir nusikalstamos veiklos ástatymus."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}
