Background {
    Title
    "<%AppName%> Setup"

    Text
    "<%AppName%>"
}

ChooseComponents {
    Title
    "Custom Setup"

    Caption
    "Selecteer de componenten die u wilt installeren en deselecteer de componenten\
     die u niet wilt installeren."

    ComponentLabel
    "Componenten"

    DescriptionLabel
    "Omschrijving"

    SpaceRequiredLabel
    "Benodigde ruimte: <%SpaceRequiredText%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CopyFiles {
    Title
    "Bestanden kopiëren "

    Caption
    "<%GroupBeingInstalledText%>"

    Message
    "<%Status%>"

    ProgressValue
    "<%InstallPercentComplete%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane1 {
    Title
    "<%AppName%> Setup"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


CustomTextPane1 {
    Title
    "Titel"

    Caption
    "Bijschrift"

    Message
    "Bericht"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane2 {
    Title
    "<%AppName%> Setup"

    Caption
    "Bijschrift"

    Text
    "Tekst gaat hier."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane3 {
    Title
    "Titel"

    Caption
    "Bijschrift"

    Message
    "Bericht"

    Text
    "Tekst gaat hier."

    NextButton
    "<%Yes%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%No%>"
}

License {
    Title
    "Licentie Overeenkomst"

    Caption
    "Lees de licentie overeenkomst aandachtig.  Gebruik de PAGE DOWN toets\
     om de rest van de overeenkomst te zien."

    Message
    "Gaat u akkoord met de licentie overeenkomst?  Als u Nee kiest zal\
     de installatie worden afgebroken.  Om <%AppName%> te installeren, moet\
     u akkoord gaan."

    Text
    "De licentie overeenkomst kunt u hier plaatsen."

    AcceptCheck
    "Ik ga akkoord met de licentie overeenkomst."

    NextButton
    "Ja"

    BackButton
    "< <%Back%>"

    CancelButton
    "Stop Installatie"
}

Readme {
    Title
    "Readme Informatie"

    Text
    "Plaats uw readme informatie hier."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SelectDestination {
    Title
    "Kies de installatie map"

    Caption
    "Dit installatie programma zal <%AppName%> in de onderstaande map installeren.\n\n
     Als u de installatie locatie wilt wijzigen klikt u op 'Selecteer map' en selecteert u een nieuwe locatie.
     Om verder te gaan met het installatieproces klikt u op Volgende."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    BrowseButton
    "<%Browse%>"

    DestinationLabel
    "Installatie map"
}

SelectProgramFolder {
    Title
    "Selecteer Programma Map"

    Caption
    "Het installatie programma zal de programma iconen toevoegen aan de onderstaande Programma map. \
     U kunt een nieuwe map aanmaken of een bestaande map selecteren uit de lijst. \
     Klik op Volgende om door te gaan."

    ProgramFolderLabel
    "Programma map:"

    FolderListLabel
    "Huidige mappen:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    AllUsersCheckbutton
    "Maak programma map voor alle gebruikers"
}

Setup {
    Title
    "Setup"

    Caption
    "Setup is de wizard aan het voorbereiden die u door de rest van het proces begeleid. Een ogenblik geduld."
}

SetupComplete {
    Title
    "Setup Afgerond"

    Caption
    "Setup is klaar met het installeren van <%AppName%> op uw computer."

    Text
    "Klik op <%Finish%> om de installatie af te ronden."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SetupType {
    Title
    "Setup Type"

    Caption
    "Kies het type setup dat u prefereerd, klik daarna op Volgende."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

StartCopyingFiles {
    Title
    "Start Kopiëren Bestanden"

    Caption
    "Het installatie programma heeft genoeg informatie om het kopiëren te starten. \
     Als u de instellingen wilt bekijken of wijzigen kunt op <%Back%> klikken.  Als u\
     tevreden bent met de instellingen klikt u op <%Next%> om het kopiëren te starten. \
     \n\nHuidige instellingen:"

    Text
    "Installatie map:\n\
     \t<%InstallDir%>

    Setup type:\n\
    \t<%InstallType%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Uninstall {
    Title
    "<%AppName%> deïnstalleren"

    Caption
    "<%GroupBeingUninstalledText%>"

    Message
    "<%Status%>"

    ProgressValue
    "<%UninstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallComplete {
    Title
    "Deïnstallatie Afgerond"

    Caption
    "Deïnstallatie succesvol afgerond."

    FinishButton
    "<%Finish%>"
}

UninstallDetails {
    Title
    "Deïnstallatie Details"

    Caption
    "De volgende fouten hebben zicht voorgedaan tijdens de deïnstallatie:"

    Errors
    "<%Errors%>"

    FinishButton
    "<%Finish%>"
}


UserInformation {
    Title
    "Gebruikers Informatie"

    Caption
    "Vul uw naam en uw bedrijfsnaam in."

    NameLabel
    "Naam:"

    CompanyLabel
    "Bedrijfsnaam:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Welcome {
    Title
    "Welkomst Scherm"

    Caption
    "Welkom bij het <%AppName%> installatie programma.  Dit programma zal\
     <%AppName%> op uw computer installeren."

    Message
    "Het is aan te raden alle overige applicaties te sluiten alvorens\
     verder te gaan met deze installatie.\n\nKlik op <%Next%> om verder\
     te gaan of op <%Cancel%> om deze installatie af te breken"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}
