Background {
    Title
    "Instalação do <%AppName%>"

    Text
    "<%AppName%>"
}

ChooseComponents {
    Title
    "Instalação Customizada"

    Caption
    "Selecione os componentes que você quer instalar e deselecione os componentes\
     que você não quer instalar."

    ComponentLabel
    "Componentes"

    DescriptionLabel
    "Descrição"

    SpaceRequiredLabel
    "Espaço necessário: <%SpaceRequiredText%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CopyFiles {
    Title
    "Copiando arquivos"

    Caption
    "<%GroupBeingInstalledText%>"

    Message
    "<%Status%>"

    ProgressValue
    "<%InstallPercentComplete%>"

    CancelButton
    "<%Cancel%>"
}

CustomBlankPane1 {
    Title
    "Instalação do <%AppName%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}


CustomTextPane1 {
    Title
    "Título"

    Caption
    "Caption"

    Message
    "Mensagem"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane2 {
    Title
    "Instalação do <%AppName%>"

    Caption
    "Caption"

    Text
    "Texto aparecerá aqui."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

CustomTextPane3 {
    Title
    "Título"

    Caption
    "Caption"

    Message
    "Mensagem"

    Text
    "Texto aparecerá aqui."

    NextButton
    "<%Yes%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%No%>"
}

License {
    Title
    "Concordância com a Licença"

    Caption
    "Por favor, leia a Concordância com a Licença.  Pressione PAGEDOWN\
     para visualizar o resto da licença."

    Message
    "Você aceita todos os termos da Licença?  Se\
     você escolher Não, A instalação será Cancelada.  Para instalar <%AppName%>, você precisa\
     aceitar todos os termos da Licença."

    Text
    "Coloque a sua Concordância com a Licença aqui."

    AcceptCheck
    "Eu aceito todos os termos desta Licença."

    NextButton
    "Sim"

    BackButton
    "< <%Back%>"

    CancelButton
    "Não"
}

Readme {
    Title
    "Informação do Readme"

    Text
    "Coloque as informações do seu Readme aqui."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SelectDestination {
    Title
    "Selecione a localização de destino"

    Caption
    "O Instalador irá instalar <%AppName%> Na seguinte pasta.\n\nPara instalar\
     nesta pasta, clique em Próximo.\n\nPara instalar em uma pasta diferente, clique\
     Navegar e selecione outra pasta.\n\nVocê pode cancelar a Instalação do\
     <%AppName%> clicando em Cancelar e o Instalador será finalizado."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    BrowseButton
    "<%Browse%>"

    DestinationLabel
    "Pasta de destino"
}

SelectProgramFolder {
    Title
    "Selecionar a pasta de Programas"

    Caption
    "Setup will add the program icons to the Program Folder listed below. \
     You may type a new folder name or select from the existing folders list. \
     Click Next to continue."

    ProgramFolderLabel
    "Pasta de Programas:"

    FolderListLabel
    "Pastas Existentes:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"

    AllUsersCheckbutton
    "Criar uma pasta de programa para todos os usuários"
}

Setup {
    Title
    "Instalação"

    Caption
    "A Instalação está preparando o Assistente do InstallJammer que irá te guiar através do\
     processo de instalação.  Por favor aguarde."
}

SetupComplete {
    Title
    "Instalação Concluída"

    Caption
    "O Instalador concluiu a instalação do <%AppName%> em seu computador."

    Text
    "Clique em Concluir para finalizar a Instalação."

    NextButton
    "<%Finish%>"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

SetupType {
    Title
    "Setup Type"

    Caption
    "Click the type of Setup you prefer, then click Next."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

StartCopyingFiles {
    Title
    "Start Copying Files"

    Caption
    "Setup has enough information to start copying the program files.  If\
     you want to review or change any settings, click Back.  If you are\
     satisfied with the settings, click Next to begin copying files. \
     \n\nCurrent Settings:"

    Text
    "Install Directory:\n\
     \t<%InstallDir%>

    Setup Type:\n\
    \t<%InstallType%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Uninstall {
    Title
    "Desinstalar <%AppName%>"

    Caption
    "<%GroupBeingUninstalledText%>"

    Message
    "<%Status%>"

    ProgressValue
    "<%UninstallPercentComplete%>"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

UninstallComplete {
    Title
    "Desinstalação Concluída"

    Caption
    "Desinstalação Concluída com Sucesso."

    FinishButton
    "<%Finish%>"
}

UninstallDetails {
    Title
    "Detalhes de Desintalação"

    Caption
    "Os seguintes erros ocorreram durante a deinstalação:"

    Errors
    "<%Errors%>"

    FinishButton
    "<%Finish%>"
}


UserInformation {
    Title
    "Informação do Usuário"

    Caption
    "Digite seu nome e a empresa onde você trabalha."

    NameLabel
    "Nome:"

    CompanyLabel
    "Empresa:"

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}

Welcome {
    Title
    "Tela de Boas Vindas"

    Caption
    "Bem vido ao programa de Instalação do <%AppName%>.  Este programa irá instalar\
     <%AppName%> em seu computador."

    Message
    "É fortemente recomendado que você feche todos os programas do Windows que você\
     esteja executando.  Clique em Próximo para continuar o programa de Instalação.\n\nAdvertência:\
     Este programa é protegido por leis de Copyright e tratados Internacionais. \n\n
     A cópia não autorizada ou a distribuição deste programa, or qualquer parte deste,\
     poderá resultar em severas penalidades cívis e criminais e será processado dentro da leis aplicáveis."

    NextButton
    "<%Next%> >"

    BackButton
    "< <%Back%>"

    CancelButton
    "<%Cancel%>"
}
