#!/bin/sh
#
# /etc/rc.d/dnsmasq: start/stop dnsmasq daemon
#

SSD=/sbin/start-stop-daemon
PROG=/usr/sbin/dnsmasq
NAME=dnsmasq
PID=/var/run/dnsmasq.pid

case $1 in
start)
	$SSD --start --pidfile $PID --exec $PROG
	;;
stop)
	$SSD --stop --remove-pidfile --retry 10 --pidfile $PID --name $NAME
	;;
restart)
	$0 stop
	$0 start
	;;
reload)
	$SSD --stop --signal HUP --pidfile $PID
	;;
status)
	$SSD --status --pidfile $PID --name $NAME
	case $? in
	0) echo "$PROG is running with pid $(cat $PID)" ;;
	1) echo "$PROG is not running but the pid file $PID exists" ;;
	3) echo "$PROG is not running" ;;
	4) echo "Unable to determine the program status" ;;
	esac
	;;
*)
	echo "usage: $0 [start|stop|restart|reload|status]"
	;;
esac

# End of file
