## $Id$
##
## BEGIN LICENSE BLOCK
##
## Copyright (C) 2002  Damon Courtney
## 
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## version 2 as published by the Free Software Foundation.
## 
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License version 2 for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the
##     Free Software Foundation, Inc.
##     51 Franklin Street, Fifth Floor
##     Boston, MA  02110-1301, USA.
##
## END LICENSE BLOCK

Action GenerateUID "Generate UID"

Property UIDType     choice "UID Type"     "UUID" {GUID UUID}
Property VirtualText short  "Virtual Text"
Help VirtualText "The virtual text variable to store the resulting UID into"

proc ::InstallJammer::actions::GenerateUID { obj } {
    global info

    $obj get UIDType     type
    $obj get VirtualText varName

    if {[string length $varName]} {
        set info($varName) [::InstallJammer::[string tolower $type]]
    }
}
