## $Id$
##
## BEGIN LICENSE BLOCK
##
## Copyright (C) 2002  Damon Courtney
## 
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## version 2 as published by the Free Software Foundation.
## 
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License version 2 for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the
##     Free Software Foundation, Inc.
##     51 Franklin Street, Fifth Floor
##     Boston, MA  02110-1301, USA.
##
## END LICENSE BLOCK

Action ModifyObject

Property ObjectState choice "Object State" "" {"" Active Inactive}
Help Active "Activate or deactivate the given object"

Property ObjectID short "Object ID"

proc ::InstallJammer::actions::ModifyObject { obj } {
    $obj properties props -subst {ObjectID}

    set id [::InstallJammer::ID $props(ObjectID)]

    if {$id eq ""} {
        return -code error "Error in Modify Object:\
            Object ID is blank"
    }

    if {![::InstallJammer::ObjExists $id]} {
        return -code error "Error in Modify Object:\
            Object \"$id\" does not exist"
    }

    if {$props(ObjectState) ne ""} {
        debug "Setting object $id to $props(ObjectState)"
        $id set Active [string equal $props(ObjectState) Active]
    }
}
