#!/bin/sh
getent group polkituser || /usr/sbin/groupadd -fg 27 polkituser
getent passwd polkituser || /usr/sbin/useradd -c "Policy Kit Daemon User" -d /dev/null -u 27 -g polkituser -s /bin/false polkituser || [ $? == 9 ]
