#!/bin/sh
getent group polkitd || /usr/sbin/groupadd -fg 27 polkitd
getent passwd polkitd || /usr/sbin/useradd -c "Policy Kit Daemon User" -d /dev/null -u 27 -g polkitd -s /bin/false polkitd || [ $? == 9 ]
