## $Id$
##
## BEGIN LICENSE BLOCK
##
## Copyright (C) 2002  Damon Courtney
## 
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## version 2 as published by the Free Software Foundation.
## 
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License version 2 for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the
##     Free Software Foundation, Inc.
##     51 Franklin Street, Fifth Floor
##     Boston, MA  02110-1301, USA.
##
## END LICENSE BLOCK

Action ChangeFilePermissions

Property Files short "Files"
Help Files "A list of file patterns separated by \; (example: */*.txt\;*/*.sh)"

Property Permissions short "Permissions" "0755"
Help Permissions "The UNIX permissions mask (in octal format)"

proc ::InstallJammer::actions::ChangeFilePermissions { obj } {
    global conf

    ## This is a UNIX-only action.  Ignore on Windows.
    if {$conf(windows)} { return }

    $obj properties props

    set perms [format %.5d [string trimleft $props(Permissions) 0]]

    foreach file [::InstallJammer::GetFilesForPattern $props(Files) -type f] {
        file attributes $file -permissions $perms
    }
}
