## $Id$
##
## BEGIN LICENSE BLOCK
##
## Copyright (C) 2002  Damon Courtney
## 
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## version 2 as published by the Free Software Foundation.
## 
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License version 2 for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the
##     Free Software Foundation, Inc.
##     51 Franklin Street, Fifth Floor
##     Boston, MA  02110-1301, USA.
##
## END LICENSE BLOCK

Action CreateFileLink

Property AddToUninstall boolean "Add to Uninstall" "Yes"
Help AddToUninstall "If this property is true, the link that is created\
    will be added to the list of files to be uninstalled."

Property LinkName installedfile "Link Name"
Help FileName "The name of the link to create on the target system"

Property LinkType choice "Link Type" "symbolic" {hard symbolic}

Property LinkTarget installedfile "Link Target"
Help FileName "The name of the target file or directory on the target system"

proc ::InstallJammer::actions::CreateFileLink { obj } {
    global conf

    $obj properties props -subst 1

    set link   [::InstallJammer::RelativeFile $props(LinkName)]
    set target [::InstallJammer::RelativeFile $props(LinkTarget)]

    if {$conf(windows)} {
        file link -$props(LinkType) $link $target
    } else {
        if {$props(LinkType) eq "hard"} {
            exec ln $target $link
        } else {
            exec ln -s $target $link
        }
    }

    if {$props(AddToUninstall)} { ::InstallJammer::LogFile $link }
}
