#!/bin/sh
#
# /etc/rc.d/inetd: start/stop inet daemon
#

case $1 in
start)
	/usr/sbin/inetd
	;;
stop)
	killall -q /usr/sbin/inetd
	;;
restart)
	$0 stop
	sleep 2
	$0 start
	;;
*)
	echo "usage: $0 [start|stop|restart]"
	;;
esac

# End of file
