ApplicationReadmeText
"<%AppName%> Llegiu-me"

Back
"Retrocedeix"

Browse
"Examinar..."

BuildFileText
"Generant <%Tail <%FileBeingInstalled%>%>..."

BuildUninstallText
"Generant el desinstal·lador..."

Cancel
"Cancel·lar"

CleanupInstallText
"Netejant la instal·lació..."

Close
"Tanca"

CreateDesktopShortcutText
"Crear icona a l'Escriptori"

CreateQuickLaunchShortcutText
"Crear icona a la Barra de Tasques"

CustomInstallDescription
"Seleccioni els components de la instal·lació."

DirectoryPermissionText
"No teniu permisos per a escriure a <%Dir%>."

ExitText
"De debò voleu sortir de la instal·lació?"

FileBeingInstalledText
"Copiant <%FileBeingInstalled%>"

FileBeingUninstalledText
"Eliminant <%FileBeingUninstalled%>"

Finish
"Finalitzar"

GroupBeingInstalledText
"Instal·lant <%GroupBeingInstalled%>..."

GroupBeingUninstalledText
"Eliminant <%GroupBeingUninstalled%>"

Help
"Ajuda"

InstallApplicationText
"Instal·lar <%AppName%>"

InstallCompleteText
"Instal·lació completa..."

InstallPrepareText
"Preparant la instal·lació..."

InstallStartupText
"Es va a instal·lar <%AppName%> en el seu equip. Voleu continuar?"

LaunchApplicationText
"Executar <%AppName%>"

Next
"Següent"

No
"No"

OK
"Si"

ProgramFilesDescription
"Arxius de Programa Comuns"

RequireRootText
"Necessiteu tenir permisos d'administrador per executar l'instal·lador."

SeparatorText
"InstallJammer"

TypicalInstallDescription
"Una instal·lació típica."

UninstallApplicationText
"Desinstal·lar <%AppName%>"

UninstallPrepareText
"Preparant la desinstal·lació..."

UpdateRegistryText
"Actualizant el Registre de Windows..."

UninstallStartupText
"S'eliminarà completament <%AppName%> del seu sistema. De debò ho desitgeu?"

UninstallLeftoverText
"No ha estat possible eliminar alguns components. Tot i així, desitgeu\
 eliminar-los? (no recomenat)"

ViewReadmeText
"Veure Llegiu-me"

Yes
"Si"


LocateJavaRuntime {
    PromptMessage
    "Si us plau, localitzeu el vostre Entorn d'Execució Java (JRE)"

    StatusMessage
    "Cercant l'Entorn d'Execució Java (JRE)..."
}

TextWindow {
    Title
    "Ròtul de la Finestra"

    Caption
    "Llegenda"

    Message
    "Missatge aquí."

    CloseButton
    "<%Close%>"
}

UnzipFile {
    StatusText
    "<%FileBeingInstalledText%>"
}
