# options: -encoding utf-8

ApplicationReadmeText
"ČtiMě pro <%AppName%>"

Back
"Zpět"

Browse
"Procházet..."

BuildFileText
"Vytváří se <%Tail <%FileBeingInstalled%>%>..."

BuildUninstallText
"Vytváří se odinstalace..."

Cancel
"Zrušit"

CleanupInstallText
"Pročisťuje se instalace..."

Close
"Zavřít"

ConsolePauseQuitText
"-- Stiskněte mezeru k pokračování nebo 'q' ke skončení --"

ConsolePauseText
"-- K pokračování stiskněte mezeru --"

ConsoleSelectDestinationText
"Kam chcete nainstalovat <%AppName%>?"

CreateDesktopShortcutText
"Vytvořit zástupce na ploše"

CreateQuickLaunchShortcutText
"Vytvořit zástupce snadného spuštění"

CustomInstallDescription
"Zvolte vlastní součásti k instalaci."

DirectoryNameErrorText
"Název složky nemůže obsahovat žádný z následujících znaků:
        \\ / : * ? \" < > |"

DirectoryPermissionText
"Nemáte oprávnění zapisovat do <%Dir%>."

DisplayName
"<%AppName%>"

DownloadingFilesText
"Stahování souborů..."

ExitText
"Opravdu chcete ukončit tento instalátor?"

FileBeingInstalledText
"Kopírování <%FileBeingInstalled%>"

FileBeingUninstalledText
"Odstraňování <%FileBeingUninstalled%>"

FileOverwriteText
"Soubor <%FileBeingInstalled%> již existuje. Chcete jej přepsat?"

Finish
"Dokončit"

GroupBeingInstalledText
"Instalace <%GroupBeingInstalled%>..."

GroupBeingUninstalledText
"Odstraňování <%GroupBeingUninstalled%>"

Help
"Nápověda"

InsertDiscText
"Vložte disk nazvaný <%RequiredDiscName%> a stiskněte OK."

InstallApplicationText
"Instalace programu <%AppName%>"

InstallationCompleteText
"Instalace dokončena."

InstallCompleteText
"Instalace souborů dokončena..."

InstallingApplicationText
"Instalace <%AppName%>..."

InstallErrorText
"Během instalace došlo k chybě."

InstallPrepareText
"Příprava na instalaci..."

InstallStartupText
"Program <%AppName%> bude nainstalován na váš počítač. Pokračovat?"

InstallTitleText
"Instalace programu <%AppName%>"

LaunchApplicationText
"Spustit <%AppName%>"

Next
"Vpřed"

No
"Ne"

OK
"OK"

PasswordIncorrectText
"Heslo není správné."

ProgramFilesDescription
"Běžné soubory programu"

PromptForDirectoryMessage
"Vyberte prosím složku a zvolte OK."

PromptForDirectoryNewFolderText
"Vytvořit novou složku"

PromptForDirectoryTitle
"Procházet složky"

PromptForRootText
"Zadejte prosím vaše heslo roota."

RequireAdministratorText
"Tento program vyžaduje pro provedení instalace práva správce systému."

RequireRootText
"Pro spuštění instalátoru musíte být root."

SelectLanguageText
"Prosím zvolte jazyk instalace"

SeparatorText
"InstallJammer"

TypicalInstallDescription
"Typická instalace."

UninstallApplicationText
"Odinstalovat <%AppName%>"

UninstallPrepareText
"Příprava odinstalace..."

UpdateRegistryText
"Aktualizace registrů Windows..."

UninstallingApplicationText
"Odinstalace <%AppName%>..."

UninstallCompleteText
"Odinstalace dokončena."

UninstallStartupText
"Program <%AppName%> bude kompletně odstraněn z vašeho systému. Opravdu to\
 chcete udělat?"

UninstallLeftoverText
"Některé součásti nemohly být odstraněny. Chcete je i přesto smazat\
 (není doporučeno)?"

UninstallTitleText
"Odinstalovat <%AppName%>"

UnpackingFilesText
"Rozbalování souborů..."

VersionHelpText
"Tento program nainstaluje aplikaci <%AppName%> verze <%Version%>."

ViewReadmeText
"Zobrazit ČtiMě"

Yes
"Ano"

ConsolePause {
    Message
    "<%ConsolePauseText%>"
}

LocateJavaRuntime {
    PromptMessage
    "Prosím sdělte nám, kde je umístěno vaše Java Runtime"

    StatusMessage
    "Hledání Java Runtime..."
}

TextWindow {
    Title
    "Název okna"

    Caption
    "Titulek"

    Message
    "Zde bude zpráva."

    CloseButton
    "<%Close%>"
}

UnzipFile {
    StatusText
    "<%FileBeingInstalledText%>"
}
