ApplicationReadmeText
"<%AppName%> Readme"

Back
"Back"

Browse
"Browse..."

BuildFileText
"Building <%Tail <%FileBeingInstalled%>%>..."

BuildUninstallText
"Building uninstall..."

Cancel
"Cancel"

CleanupInstallText
"Cleaning up install..."

Close
"Close"

ConsolePauseQuitText
"-- Press space to continue or 'q' to quit --"

ConsolePauseText
"-- Press space to continue --"

ConsoleSelectDestinationText
"Where do you want to install <%AppName%>?"

CreateDesktopShortcutText
"Create Desktop Shortcut"

CreateQuickLaunchShortcutText
"Create Quick Launch Shortcut"

CustomInstallDescription
"Select custom components for installation."

DirectoryNameErrorText
"A directory name cannot contain any of the following characters:
        \\ / : * ? \" < > |"

DirectoryNotEmptyText
"<%Dir%> is not empty."

DirectoryPermissionText
"You do not have permission to write to <%Dir%>."

DisplayName
"<%AppName%>"

DownloadingFilesText
"Downloading files..."

ErrorTitle
"Install Error"

ExitText
"Are you sure you want to exit this setup?"

ExitTitle
"Exit Setup"

FileBeingInstalledText
"Copying <%FileBeingInstalled%>"

FileBeingUninstalledText
"Removing <%FileBeingUninstalled%>"

FileOverwriteText
"The file <%FileBeingInstalled%> already exists.  Do you want to overwrite it?"

Finish
"Finish"

GroupBeingInstalledText
"Installing <%GroupBeingInstalled%>..."

GroupBeingUninstalledText
"Removing <%GroupBeingUninstalled%>"

Help
"Help"

InsertDiscText
"Insert the disc labeled <%RequiredDiscName%> and then click OK."

InstallApplicationText
"Install <%AppName%>"

InstallationCompleteText
"Installation complete."

InstallCompleteText
"File installation complete..."

InstallingApplicationText
"Installing <%AppName%>..."

InstallErrorText
"An error has occurred during installation."

InstallPrepareText
"Preparing to install..."

InstallStartupText
"This will install <%AppName%> on your computer.  Continue?"

InstallTitleText
"<%AppName%> Setup"

LaunchApplicationText
"Launch <%AppName%>"

Next
"Next"

No
"No"

OK
"OK"

PasswordIncorrectText
"Password is incorrect."

ProgramFilesDescription
"Common Program Files"

PromptForAdministratorText
"This program requires administrator privileges.  Please enter your password."

PromptForDirectoryMessage
"Please choose a directory, then select OK."

PromptForDirectoryNewFolderText
"Make New Folder"

PromptForDirectoryTitle
"Browse for Folder"

PromptForRootText
"Please enter your root password."

RequireAdministratorText
"This program requires administrator privileges to install."

RequireRootText
"You must be root to run this installer."

RequireRootTitleText
"Root Required"

RequireRootUninstallText
"You must be root to uninstall this application."

SelectLanguageText
"Please select the installation language"

SeparatorText
"InstallJammer"

String.database.entries
"database entries"

String.directories
"directories"

String.environment.variables
"environment variables"

String.files
"files"

String.package.entries
"package entries"

String.registry.entries
"registry entries"

String.shortcuts
"shortcuts"

TypicalInstallDescription
"A typical installation."

UninstallApplicationText
"Uninstall <%AppName%>"

UninstallPrepareText
"Preparing to uninstall..."

UpdateRegistryText
"Updating Windows Registry..."

UninstallingApplicationText
"Uninstalling <%AppName%>..."

UninstallCompleteText
"Uninstall complete."

UninstallStartupText
"This will completely remove <%AppName%> from your system.  Are you sure\
 you want to do this?"

UninstallLeftoverText
"Some components could not be removed.  Do you wish to delete them anyway\
 (not recommended)?"

UninstallPrepareText
"Preparing to uninstall..."

UninstallTitleText
"Uninstall <%AppName%>"

UnpackingFilesText
"Unpacking files..."

VersionHelpText
"This program will install <%AppName%> version <%Version%>."

ViewReadmeText
"View Readme"

Yes
"Yes"

ConsolePause {
    Message
    "<%ConsolePauseText%>"
}

LocateJavaRuntime {
    PromptMessage
    "Please tell us where your Java Runtime is located"

    StatusMessage
    "Locating Java Runtime..."
}

TextWindow {
    Title
    "Window Title"

    Caption
    "Caption"

    Message
    "Message goes here."

    CloseButton
    "<%Close%>"
}

UnzipFile {
    StatusText
    "<%FileBeingInstalledText%>"
}
