ApplicationReadmeText
"<%AppName%> Léeme"

Back
"Atrás"

Browse
"Examinar..."

BuildFileText
"Generando <%Tail <%FileBeingInstalled%>%>..."

BuildUninstallText
"Generando desinstalador..."

Cancel
"Cancelar"

CleanupInstallText
"Limpiando instalación..."

Close
"Cerrar"

CreateDesktopShortcutText
"Crear icono en Escritorio"

CreateQuickLaunchShortcutText
"Crear icono en Barra de Tareas"

CustomInstallDescription
"Seleccione los componentes de la instalación."

DirectoryPermissionText
"No tiene permisos para escribir en <%Dir%>."

ExitText
"¿Seguro que desea salir de la instalación?"

FileBeingInstalledText
"Copiando <%FileBeingInstalled%>"

FileBeingUninstalledText
"Borrando <%FileBeingUninstalled%>"

Finish
"Finalizar"

GroupBeingInstalledText
"Instalando <%GroupBeingInstalled%>..."

GroupBeingUninstalledText
"Borrando <%GroupBeingUninstalled%>"

Help
"Ayuda"

InstallApplicationText
"Instalar <%AppName%>"

InstallCompleteText
"Instalación completa..."

InstallPrepareText
"Preparando instalación..."

InstallStartupText
"Se va a instalar <%AppName%> en su equipo.  ¿Continuar?"

LaunchApplicationText
"Ejecutar <%AppName%>"

Next
"Siguiente"

No
"No"

OK
"OK"

ProgramFilesDescription
"Archivos de Programa Comunes"

RequireRootText
"Necesita tener permisos de administrador para ejecutar el instalador."

SeparatorText
"InstallJammer"

TypicalInstallDescription
"Una instalación típica."

UninstallApplicationText
"Desinstalar <%AppName%>"

UninstallPrepareText
"Preparando desinstalación..."

UpdateRegistryText
"Actualizando Registro de Windows..."

UninstallStartupText
"Se eliminará completamente <%AppName%> de su sistema. ¿Seguro que desea esto?"

UninstallLeftoverText
"Algunos componentes no pudieron ser eliminados. ¿Desea borrarlos de todos\
 modos? (no recomendado)"

ViewReadmeText
"Ver Léeme"

Yes
"Sí"


LocateJavaRuntime {
    PromptMessage
    "Por favor, localice su Entorno de Ejecución Java (JRE)"

    StatusMessage
    "Buscando Entorno de Ejecución Java (JRE)..."
}

TextWindow {
    Title
    "Título de la Ventana"

    Caption
    "Leyenda"

    Message
    "Mensaje aquí."

    CloseButton
    "<%Close%>"
}

UnzipFile {
    StatusText
    "<%FileBeingInstalledText%>"
}
