ApplicationReadmeText
"<%AppName%> Leggimi"

Back
"Indietro"

Browse
"Sfoglia..."

BuildFileText
"Generazione di <%Tail <%FileBeingInstalled%>%>..."

BuildUninstallText
"Generazione della disinstallazione..."

Cancel
"Annulla"

CleanupInstallText
"Pulizia dei file di installazione..."

Close
"Chiudi"

ConsolePauseQuitText
"-- Premere spazio per proseguire o 'q' per uscire --"

ConsolePauseText
"-- Premere spazio per proseguire --"

ConsoleSelectDestinationText
"Dove si desidera installare <%AppName%>?"

CreateDesktopShortcutText
"Crea collegamento sul Desktop"

CreateQuickLaunchShortcutText
"Crea collegamento in Avvio rapido"

CustomInstallDescription
"Seleziona in modo personalizzato le parti da installare."

DirectoryPermissionText
"Non si dispone dei permessi di scrittura in <%Dir%>."

DisplayName
"<%AppName%>"

DownloadingFilesText
"Scaricamento dei file..."

ExitText
"Si è sicuri di voler uscire dal programma di installazione?"

FileBeingInstalledText
"Copia di <%FileBeingInstalled%>"

FileBeingUninstalledText
"Rimozione di <%FileBeingUninstalled%>"

FileOverwriteText
"Il file <%FileBeingInstalled%> esiste già. Lo si vuole sovrascrivere?"

Finish
"Fine"

GroupBeingInstalledText
"Installazione di <%GroupBeingInstalled%>..."

GroupBeingUninstalledText
"Rimozione di <%GroupBeingUninstalled%>"

Help
"Aiuto"

InstallApplicationText
"Installa <%AppName%>"

InstallationCompleteText
"Installazione completata."

InstallCompleteText
"Completamento dell'installazione dei file..."

InstallingApplicationText
"Installazione di <%AppName%>..."

InstallPrepareText
"Preparazione dell'installazione..."

InstallStartupText
"<%AppName%> sarà installato sul computer. Proseguire?"

InstallTitleText
"Installazione di <%AppName%>"

LaunchApplicationText
"Eseguire <%AppName%>"

Next
"Avanti"

No
"No"

OK
"OK"

PasswordIncorrectText
"La parola chiave è errata."

ProgramFilesDescription
"Programmi Comuni"

PromptForDirectoryMessage
"Si prega di scegliere una directory, poi selezionare OK."

PromptForDirectoryTitle
"Sfoglia le cartelle"

PromptForRootText
"Si prega di inserire la parola chiave di root."

RequireRootText
"E' necessario essere root per eseguire il programma di installazione."

SeparatorText
"InstallJammer"

TypicalInstallDescription
"Installazione tipica."

UninstallApplicationText
"Disinstalla <%AppName%>"

UninstallPrepareText
"Preparazione della disinstallazione..."

UpdateRegistryText
"Aggiornamento del Registro di Windows..."

UninstallingApplicationText
"Disinstallazione di <%AppName%>..."

UninstallCompleteText
"Disinstallazione completata."

UninstallStartupText
"<%AppName%> sarà rimosso completamente dal sistema. Si è sicuri di voler\
 procedere?"

UninstallLeftoverText
"Alcune parti non possono essere rimosse. Si desidera cancellarle comunque\
 (sconsigliato)?"

UninstallTitleText
"Disinstalla <%AppName%>"

UnpackingFilesText
"Decompressione dei file..."

VersionHelpText
"Il programma sta per installare <%AppName%> nella versione <%Version%>."

ViewReadmeText
"Visualizza il file Leggimi"

Yes
"Sì"

ConsolePause {
    Message
    "<%ConsolePauseText%>"
}

LocateJavaRuntime {
    PromptMessage
    "Si prega di comunicare dove si trova la Java Runtime"

    StatusMessage
    "Individuazione della Java Runtime in corso..."
}

TextWindow {
    Title
    "Titolo della finestra"

    Caption
    "Didascalia"

    Message
    "Il messaggio va qui."

    CloseButton
    "<%Close%>"
}

UnzipFile {
    StatusText
    "<%FileBeingInstalledText%>"
}
