ApplicationReadmeText
"<%AppName%> Skaityk"

Back
"Atgal"

Browse
"Parinkti..."

BuildFileText
"Kuriamas <%Tail <%FileBeingInstalled%>%>..."

BuildUninstallText
"Kuriama ðalinimo programa..."

Cancel
"Atsisakyti"

CleanupInstallText
"Iðvalomas diegimas..."

Close
"Uþverti"

ConsolePauseQuitText
"-- Spauskite tarpà tam kad tæsti arba 'q' kad baigti --"

ConsolePauseText
"-- Spauskite tarpà tam kad tæsti --"

ConsoleSelectDestinationText
"Kur norëtumëte ádiegti <%AppName%>?"

CreateDesktopShortcutText
"Sukurti darbalaukio ðaukiná"

CreateQuickLaunchShortcutText
"Sukurti sparèiosios paleisties ðaukiná"

CustomInstallDescription
"Pasirinkiti komponentus ádiegimui."

DirectoryNameErrorText
"Katalogas negali turëti ðiø þenklø:
        \\ / : * ? \" < > |"

DirectoryPermissionText
"Jûs neturite teisës raðyti á <%Dir%>."

DisplayName
"<%AppName%>"

DownloadingFilesText
"Atsiunèiami failai..."

ExitText
"Ar jûs ásitikinæs, kad norite iðeiti ið ðios diegimo programos?"

FileBeingInstalledText
"Kopijuojama <%FileBeingInstalled%>"

FileBeingUninstalledText
"Ðalinama <%FileBeingUninstalled%>"

FileOverwriteText
"Failas <%FileBeingInstalled%> jau yra. Ar norëtumëte já perraðyti?"

Finish
"Pabaiga"

GroupBeingInstalledText
"Diegiama <%GroupBeingInstalled%>..."

GroupBeingUninstalledText
"Ðalinama <%GroupBeingUninstalled%>"

Help
"Pagalba"

InstallApplicationText
"Ádiegti <%AppName%>"

InstallationCompleteText
"Diegimas baigtas."

InstallCompleteText
"Failo diegimas baigtas..."

InstallingApplicationText
"Diegema <%AppName%>..."

InstallErrorText
"Diegimo metu ávyko klaida."

InstallPrepareText
"Ruoðiamasi diegimui..."

InstallStartupText
"Tai ádiegs <%AppName%> á jûsø kompiuterá. Tæsti?"

InstallTitleText
"<%AppName%> Ádiegimo programa"

LaunchApplicationText
"Paleisti <%AppName%>"

Next
"Toliau"

No
"Ne"

OK
"Gerai"

PasswordIncorrectText
"Slaptaþodis yra neteisingas."

ProgramFilesDescription
"Bendri Programos Failai"

PromptForDirectoryMessage
"Praðom pasirinkti katalogà, tada pasirinkti Gerai."

PromptForDirectoryNewFolderText
"Sukurti naujà katalogà"

PromptForDirectoryTitle
"Parinkti katalogà"

PromptForRootText
"Praðom ávesti jûsø root slaptaþodá."

RequireRootText
"Jûs turite bûti root kad paleistumëte ðià diegimo programà."

SeparatorText
"InstallJammer"

TypicalInstallDescription
"Tipinis diegimas."

UninstallApplicationText
"Paðalinti programà <%AppName%>"

UninstallPrepareText
"Ruoðiamasi paðalinti programà..."

UpdateRegistryText
"Atnaujinamas Windows registras..."

UninstallingApplicationText
"Paðalinama programa <%AppName%>..."

UninstallCompleteText
"Programos paðalinimas atliktas."

UninstallStartupText
"Tai visiðkai paðalins <%AppName%> ið jûsø sistemos.  Ar jûs ásitikinæs\
 kad norite tai atlikti?"

UninstallLeftoverText
"Kai kurie komponentai negali bûti paðalinti. Ar norëtumëte juos paðalinti\
 betkuriuo atvëju (nerekomenduojama)?"

UninstallTitleText
"Programos paðalinimas <%AppName%>"

UnpackingFilesText
"Iðpakuojami failai..."

VersionHelpText
"Programa <%AppName%> versija <%Version%> bus ádiegta."

ViewReadmeText
"Perþiûrëti apraðymà"

Yes
"Taip"

ConsolePause {
    Message
    "<%ConsolePauseText%>"
}

LocateJavaRuntime {
    PromptMessage
    "Praðom pasakyti kur jûsø Java Runtime randasi"

    StatusMessage
    "Ieðkome Java Runtime..."
}

TextWindow {
    Title
    "Lango Antraðtë"

    Caption
    "Pavadinimas"

    Message
    "Praneðimas ávedamas èia."

    CloseButton
    "<%Close%>"
}

UnzipFile {
    StatusText
    "<%FileBeingInstalledText%>"
}
