ApplicationReadmeText
"<%AppName%> Readme"

Back
"Terug"

Browse
"Bladeren..."

BuildFileText
"Bouwen <%Tail <%FileBeingInstalled%>%>..."

BuildUninstallText
"Bouwen deïnstallatie..."

Cancel
"Annuleren"

CleanupInstallText
"Opschonen installatie..."

Close
"Sluiten"

ConsolePauseQuitText
"-- Druk op spatie om door te gaan of op 'q' om te stoppen --"

ConsolePauseText
"-- Druk op spatie om door te gaan --"

ConsoleSelectDestinationText
"Waar wilt u <%AppName%> installeren?"

CreateDesktopShortcutText
"Maak bureaublad snelkoppeling"

CreateQuickLaunchShortcutText
"Maak Snel Start snelkoppeling"

CustomInstallDescription
"Selecteer afzonderlijke componenten voor installatie."

DirectoryPermissionText
"U heeft geen toestemming om te schrijven naar <%Dir%>."

DisplayName
"<%AppName%>"

DownloadingFilesText
"Bestanden downloaden..."

ExitText
"Weet u zeker dat u wilt stoppen met deze installatie?"

FileBeingInstalledText
"Kopiëren <%FileBeingInstalled%>"

FileBeingUninstalledText
"Verwijderen <%FileBeingUninstalled%>"

FileOverwriteText
"Het bestand <%FileBeingInstalled%> bestaat al.  Wilt u het overschrijven?"

Finish
"Klaar"

GroupBeingInstalledText
"Installeren <%GroupBeingInstalled%>..."

GroupBeingUninstalledText
"Verwijderen <%GroupBeingUninstalled%>"

Help
"Help"

InstallApplicationText
"Installeer <%AppName%>"

InstallationCompleteText
"Installatie afgerond."

InstallCompleteText
"Bestand installatie afgerond..."

InstallingApplicationText
"<%AppName%> installeren..."

InstallPrepareText
"Installatie voorbereiden..."

InstallStartupText
"Dit zal <%AppName%> op uw computer installeren.  Doorgaan?"

InstallTitleText
"<%AppName%> Setup"

LaunchApplicationText
"Start <%AppName%>"

Next
"Volgende"

No
"Nee"

OK
"OK"

PasswordIncorrectText
"Wachtwoord is onjuist."

ProgramFilesDescription
"Algemene bestanden"

PromptForDirectoryMessage
"Selecteer een directory, klik daarna op OK."

PromptForDirectoryTitle
"Blader naar map"

PromptForRootText
"Vul uw root wachtwoord in."

RequireRootText
"U moet root zijn om dit programma te installeren."

SeparatorText
"SemLab"

TypicalInstallDescription
"Een standaard installatie."

UninstallApplicationText
"Verwijderen <%AppName%>"

UninstallPrepareText
"Deïnstallatie voorbereiden..."

UpdateRegistryText
"Windows Register bijwerken..."

UninstallingApplicationText
"<%AppName%> verwijderen..."

UninstallCompleteText
"Deïnstallatie klaar."

UninstallStartupText
"Dit verwijderd <%AppName%> geheel van uw systeem.  Weet u zeker\
 dat u dit wilt doen?"

UninstallLeftoverText
"Sommige componenten konden niet worden verwijderd.  Wilt u ze toch verwijderen\
 (niet aangeraden)?"

UninstallTitleText
"Verwijder <%AppName%>"

UnpackingFilesText
"Bestanden uitpakken..."

VersionHelpText
"Dit programma zal <%AppName%> versie <%Version%> installeren."

ViewReadmeText
"Bekijk Readme"

Yes
"Ja"

ConsolePause {
    Message
    "<%ConsolePauseText%>"
}

LocateJavaRuntime {
    PromptMessage
    "Wijs uw Java Runtime locatie aan"

    StatusMessage
    "Java Runtime lokaliseren..."
}

TextWindow {
    Title
    "Scherm titel"

    Caption
    "Bijschrift"

    Message
    "Bericht gaat hier."

    CloseButton
    "<%Close%>"
}

UnzipFile {
    StatusText
    "<%FileBeingInstalledText%>"
}
