# options: -encoding utf-8

ApplicationReadmeText
"<%AppName%> Readme"

Back
"Wstecz"

Browse
"Przeglądaj..."

BuildFileText
"Budowanie <%Tail <%FileBeingInstalled%>%>..."

BuildUninstallText
"Budowanie deinstalatora..."

Cancel
"Anuluj"

CleanupInstallText
"Czyszczenie instalacji..."

Close
"Zamknij"

ConsolePauseQuitText
"-- Wciśnij spację, aby kontynuować lub 'q', aby wyjść --"

ConsolePauseText
"-- Wciśnij spację, aby kontynuować --"

ConsoleSelectDestinationText
"Gdzie chcesz zainstalować <%AppName%>?"

CreateDesktopShortcutText
"Utwórz skrót na pulpicie"

CreateQuickLaunchShortcutText
"Utwórz skrót szybkiego uruchamiania"

CustomInstallDescription
"Zaznacz wybrane komponenty do instalacji."

DirectoryPermissionText
"Nie masz uprawniwń, aby zapisywać w <%Dir%>."

DownloadingFilesText
"Pobieranie plików..."

ExitText
"Czy na pewno chcesz opuścić instalator?"

FileBeingInstalledText
"Kopiowanie <%FileBeingInstalled%>"

FileBeingUninstalledText
"Usuwanie <%FileBeingUninstalled%>"

FileOverwriteText
"Plik <%FileBeingInstalled%> już istnieje.  Czy chcesz go naspisać?"

Finish
"Zakończ"

GroupBeingInstalledText
"Instalowanie <%GroupBeingInstalled%>..."

GroupBeingUninstalledText
"Usuwanie <%GroupBeingUninstalled%>"

Help
"Pomoc"

InstallApplicationText
"Instaluj <%AppName%>"

InstallationCompleteText
"Instalacja zakończona."

InstallCompleteText
"Instalacja pliku zakończona..."

InstallingApplicationText
"Instalowanie <%AppName%>..."

InstallPrepareText
"Przygotowywanie do instalacji..."

InstallStartupText
"Instalator zainstaluje <%AppName%> na twoim komputerze. Kontynuować?"

LaunchApplicationText
"Uruchom <%AppName%>"

Next
"Dalej"

No
"Nie"

OK
"OK"

ProgramFilesDescription
"Common Program Files"

PromptForRootText
"Proszę wpisać hasło administratora."

RequireRootText
"Musisz być administratorem (root), aby uruchomić ten instalator."

SeparatorText
"InstallJammer"

TypicalInstallDescription
"Instalacja typowa."

UninstallApplicationText
"Usuń <%AppName%>"

UninstallPrepareText
"Przygotowywanie do deinstalacji..."

UpdateRegistryText
"Uaktualnianie rejestru Windows..."

UninstallingApplicationText
"Deinstalacja <%AppName%>..."

UninstallCompleteText
"Deinstalacja zakończona."

UninstallStartupText
"<%AppName%> zostanie kompletnie usunięty z twojego systemu.  Czy\
 na pewno chcesz tego?"

UninstallLeftoverText
"Niektóre komponenty nie mogły zostać usunięte.  Czy pomimo to chcesz\
 je usunąć (niezalecane)?"

VersionHelpText
"Ten program zainstaluje <%AppName%> w wersji <%Version%>."

ViewReadmeText
"Pokaż Readme"

Yes
"Tak"

ConsolePause {
    Message
    "<%ConsolePauseText%>"
}

LocateJavaRuntime {
    PromptMessage
    "Proszę powiedzieć, gdzie zainstalowano Java Runtime Environment."

    StatusMessage
    "Szukanie Java Runtime..."
}

TextWindow {
    Title
    "Okno tytułowe"

    Caption
    "Nagłówek"

    Message
    "Wyjście wiadomości."

    CloseButton
    "<%Close%>"
}

UnzipFile {
    StatusText
    "<%FileBeingInstalledText%>"
}
