ApplicationReadmeText
"<%AppName%> Readme"

Back
"Voltar"

Browse
"Navegar..."

BuildFileText
"Construindo <%Tail <%FileBeingInstalled%>%>..."

BuildUninstallText
"Construindo desinstalado..."

Cancel
"Cancelar"

CleanupInstallText
"Limpando instalação..."

Close
"Fechar"

CreateDesktopShortcutText
"Criando atalho no Desktop"

CreateQuickLaunchShortcutText
"Criação de atalho na barra de inicialização rápida"

CustomInstallDescription
"Selecionar componentes personalizados para instalação."

DirectoryPermissionText
"Você não tem permissão para escrever em <%Dir%>."

ExitText
"Você está certo que deseja sair do instalador?"

FileBeingInstalledText
"Copiando <%FileBeingInstalled%>"

FileBeingUninstalledText
"Removendo <%FileBeingUninstalled%>"

Finish
"Concluir"

GroupBeingInstalledText
"Instalando <%GroupBeingInstalled%>"

GroupBeingUninstalledText
"Removendo <%GroupBeingUninstalled%>"

Help
"Ajuda"

InstallApplicationText
"Instalar <%AppName%>"

InstallCompleteText
"Instalação de arquivos completa..."

InstallPrepareText
"Preparando para instalar..."

InstallStartupText
"Será instalado <%AppName%> em seu computador.  Continuar?"

LaunchApplicationText
"Iniciar <%AppName%>"

Next
"Próximo"

No
"Não"

OK
"OK"

ProgramFilesDescription
"Arquivos comuns de programa"

RequireRootText
"Você precisa ser root para executar o instalador."

SeparatorText
"InstallJammer"

TypicalInstallDescription
"Uma instalação típica."

UninstallApplicationText
"Desinstalar <%AppName%>"

UninstallPrepareText
"Preparando para desinstalar..."

UpdateRegistryText
"Atualizando Registro do Windows..."

UninstallStartupText
"<%AppName%> será removido completamento do seu computador.  Você tem\
certeza que deseja continuar?"

UninstallLeftoverText
"Alguns componentes não puderam ser removidos. Você deseja deletá-los assim mesmo\
 (não recomendado)?"

VersionHelpText
"Este programa irá instalar <%AppName%> versão <%Version%>."

ViewReadmeText
"Veja o Readme"

Yes
"Sim"


LocateJavaRuntime {
    PromptMessage
    "Por favor informe onde o Java Runtime está instalado"

    StatusMessage
    "Localizando Java Runtime..."
}

TextWindow {
    Title
    "Título da Janela"

    Caption
    "Caption"

    Message
    "Mensagens aparecerão aqui."

    CloseButton
    "<%Close%>"
}

UnzipFile {
    StatusText
    "<%FileBeingInstalledText%>"
}
