ApplicationReadmeText
"Информация о <%AppName%>"

Back
"Назад"

Browse
"Просмотр..."

BuildFileText
"Создаётся <%Tail <%FileBeingInstalled%>%>..."

BuildUninstallText
"Создаётся программа деинсталляции..."

Cancel
"Отмена"

CleanupInstallText
"Чистка программы инсталляции..."

Close
"Закрыть"

ConsolePauseQuitText
"-- Нажмите пробел для продолжения или 'q' для выхода --"

ConsolePauseText
"-- Нажмите пробел для продолжения --"

ConsoleSelectDestinationText
"Где вы хотите установить <%AppName%>?"

CreateDesktopShortcutText
"Создать ярлык на рабочем столе"

CreateQuickLaunchShortcutText
"Создать ярлык в панели быстрого запуска"

CustomInstallDescription
"Выберите компоненты для установки."

DirectoryPermissionText
"Нет доступа на запись в <%Dir%>."

DisplayName
"<%AppName%>"

DownloadingFilesText
"Идёт загрузка файлов..."

ExitText
"Вы уверены, что хотите завершить работу программы установки ?"

FileBeingInstalledText
"Копируется <%FileBeingInstalled%>"

FileBeingUninstalledText
"Удаляется <%FileBeingUninstalled%>"

FileOverwriteText
"Файл <%FileBeingInstalled%> уже существует.  Желаете перезаписать его ?"

Finish
"Готово"

GroupBeingInstalledText
"Устанавливается <%GroupBeingInstalled%>..."

GroupBeingUninstalledText
"Удаляется <%GroupBeingUninstalled%>"

Help
"Помощь"

InstallApplicationText
"Установка <%AppName%>"

InstallationCompleteText
"Установка завершена."

InstallCompleteText
"Установка файла завершена."

InstallingApplicationText
"Устанавливается <%AppName%>..."

InstallPrepareText
"Подготовка к установке..."

InstallStartupText
"<%AppName%> будет установлена на вашем компьютере. Продолжить ?"

InstallTitleText
"Установка <%AppName%>"

LaunchApplicationText
"Запуск <%AppName%>"

Next
"Далее"

No
"Нет"

OK
"OK"

PasswordIncorrectText
"Неверный пароль."

ProgramFilesDescription
"Общие Программные Файлы"

PromptForDirectoryMessage
"Пожалуйста, выберите каталог и щёлкните на OK."

PromptForDirectoryTitle
"Выбор каталога"

PromptForRootText
"Пожалуйста, введите пароль пользователя root."

RequireRootText
"Вы должны иметь права пользователя root для запуска этой программы установки."

SeparatorText
"InstallJammer"

TypicalInstallDescription
"Стандартная установка."

UninstallApplicationText
"Деинсталляция <%AppName%>"

UninstallPrepareText
"Идёт подготовка к деинсталляции..."

UpdateRegistryText
"Вносятся изменения в реестр Windows..."

UninstallingApplicationText
"Идёт деинсталляция <%AppName%>..."

UninstallCompleteText
"Деинсталляция завершена."

UninstallStartupText
"<%AppName%> будет полностью удалена из вашей системы. Вы уверены, что\
 собираетесь это сделать ?"

UninstallLeftoverText
"Некоторые компоненты не могут быть удалены. Вы всё-таки желаете их удалить\
 (не рекомендуется) ?"

UninstallTitleText
"Деинсталлировать <%AppName%>"

UnpackingFilesText
"Идёт распаковка файлов..."

VersionHelpText
"Эта программа установит <%AppName%> <%Version%>."

ViewReadmeText
"Просмотр информации"

Yes
"Да"

ConsolePause {
    Message
    "<%ConsolePauseText%>"
}

LocateJavaRuntime {
    PromptMessage
    "Пожалуйста, укажите где находится Java Runtime"

    StatusMessage
    "Идёт поиск Java Runtime..."
}

TextWindow {
    Title
    "Заголовок окна"

    Caption
    "Подпись"

    Message
    "Здесь должно быть сообщение."

    CloseButton
    "<%Close%>"
}

UnzipFile {
    StatusText
    "<%FileBeingInstalledText%>"
}
