#!/bin/sh

name=libglade
DTD_CAT=/etc/xml/dtd/$name/2.0/catalog
DTD_PATH=file:///usr/share/xml/dtd/$name/2.0/glade-2.0.dtd
DTD_URL=http://glade.gnome.org/glade-2.0.dtd

xmlcatalog --sgml --noout --add "delegateSystem" \
  "$DTD_URL" "$DTD_PATH" $DTD_CAT

rm /delegateSystem

# End of file
