#!/bin/bash
# https://github.com/step-/gtk-stock-icons2
# Extends https://forum.porteus.org/viewtopic.php?p=8614#p8614
# Icon name data: https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html
gtkdialog -c -s >/dev/null << EOW
$(
awk << \EOF '
  BEGIN { print "<window title=\"gtk stock icons\" icon-name=\"dialog-information\"><vbox><hbox>" }
  { printf "<pixmap icon_size=\"5\" tooltip-text=\"%s\"><input file stock=\"%s\"></input></pixmap>\n", $0, $1 }
  NR % 21 == 0 { print "</hbox><hbox>" }
  END { print "<text><label>\"\"</label></text></hbox><button ok></button></vbox></window>" }
'
gtk-about has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'help-about' or the label '_About'.
gtk-add has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'list-add' or the label '_Add'.
gtk-apply has been deprecated since version 3.10 and should not be used in newly-written code. Do not use an icon. Use label '_Apply'.
gtk-bold has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'format-text-bold'.
gtk-cancel has been deprecated since version 3.10 and should not be used in newly-written code. Do not use an icon. Use label '_Cancel'.
gtk-caps-lock-warning has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'dialog-warning-symbolic'.
gtk-cdrom has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'media-optical'.
gtk-clear has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'edit-clear'.
gtk-close has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'window-close' or the label '_Close'.
gtk-color-picker has been deprecated since version 3.10 and should not be used in newly-written code.
gtk-convert has been deprecated since version 3.10 and should not be used in newly-written code.
gtk-connect has been deprecated since version 3.10 and should not be used in newly-written code.
gtk-copy has been deprecated since version 3.10 and should not be used in newly-written code. Use the named icon 'edit-copy' or the label '_Copy'.
gtk-cut has been deprecated since version 3.10 and should not be used in newly-written code. Use the named icon 'edit-cut' or the label 'Cu-t'.
gtk-delete has been deprecated since version 3.10 and should not be used in newly-written code. Use the named icon 'edit-delete' or the label '_Delete'.
gtk-dialog-authentication has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'dialog-password'.
dialog-error has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'dialog-error'.
dialog-info has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'dialog-information'.
dialog-question has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'dialog-question'.
gtk-dialog-warning has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'dialog-warning'.
gtk-directory has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'folder'.
gtk-discard has been deprecated since version 3.10 and should not be used in newly-written code.
gtk-disconnect has been deprecated since version 3.10 and should not be used in newly-written code.
gtk-dnd has been deprecated since version 3.10 and should not be used in newly-written code.
gtk-dnd-multiple has been deprecated since version 3.10 and should not be used in newly-written code.
gtk-edit has been deprecated since version 3.10 and should not be used in newly-written code.
gtk-execute has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'system-run'.
gtk-file has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'text-x-generic'.
gtk-find has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'edit-find'.
gtk-find-and-replace has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'edit-find-replace'.
gtk-floppy has been deprecated since version 3.10 and should not be used in newly-written code.
gtk-fullscreen has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'view-fullscreen'.
gtk-goto-bottom has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'go-bottom'.
gtk-goto-first has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'go-first'.
gtk-goto-last has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'go-last'.
gtk-goto-top has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'go-top'.
gtk-go-back has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'go-previous'.
gtk-go-down has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'go-down'.
gtk-go-forward has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'go-next'.
gtk-go-up has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'go-up'.
gtk-harddisk has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'drive-harddisk'.
gtk-help has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'help-browser'.
gtk-home has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'go-home'.
gtk-indent has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'format-indent-more'.
gtk-index has been deprecated since version 3.10 and should not be used in newly-written code.
gtk-info has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'dialog-information'.
gtk-italic has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'format-text-italic'.
gtk-jump-to has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'go-jump'.
gtk-justify-center has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'format-justify-center'.
gtk-justify-fill has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'format-justify-fill'.
gtk-justify-left has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'format-justify-left'.
gtk-justify-right has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'format-justify-right'.
gtk-leave-fullscreen has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'view-restore'.
gtk-media-forward has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'media-seek-forward' or the label '_Forward'.
gtk-media-next has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'media-skip-forward' or the label '_Next'.
gtk-media-pause has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'media-playback-pause' or the label 'P-ause'.
gtk-media-play has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'media-playback-start' or the label '_Play'.
gtk-media-previous has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'media-skip-backward' or the label 'Pre-vious'.
gtk-media-record has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'media-record' or the label '_Record'.
gtk-media-rewind has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'media-seek-backward' or the label 'R-ewind'.
gtk-media-stop has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'media-playback-stop' or the label '_Stop'.
gtk-missing-image has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'image-missing'.
gtk-network has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'network-workgroup'.
gtk-new has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'document-new' or the label '_New'.
gtk-no has been deprecated since version 3.10 and should not be used in newly-written code.
gtk-ok has been deprecated since version 3.10 and should not be used in newly-written code. Do not use an icon. Use label '_OK'.
gtk-open has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'document-open' or the label '_Open'.
gtk-orientation-landscape has been deprecated since version 3.10 and should not be used in newly-written code.
gtk-orientation-portrait has been deprecated since version 3.10 and should not be used in newly-written code.
gtk-orientation-reverse-landscape has been deprecated since version 3.10 and should not be used in newly-written code.
gtk-orientation-reverse-portrait has been deprecated since version 3.10 and should not be used in newly-written code.
gtk-page-setup has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'document-page-setup' or the label 'Page Set-up'.
gtk-paste has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'edit-paste' or the label '_Paste'.
gtk-preferences has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'preferences-system' or the label '_Preferences'.
gtk-print has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'document-print' or the label '_Print'.
gtk-print-error has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'printer-error'.
gtk-print-paused has been deprecated since version 3.10 and should not be used in newly-written code.
gtk-print-preview has been deprecated since version 3.10 and should not be used in newly-written code. Use label 'Pre-view'.
gtk-print-report has been deprecated since version 3.10 and should not be used in newly-written code.
gtk-print-warning has been deprecated since version 3.10 and should not be used in newly-written code.
gtk-properties has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'document-properties' or the label '_Properties'.
gtk-quit has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'application-exit' or the label '_Quit'.
gtk-redo has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'edit-redo' or the label '_Redo'.
gtk-refresh has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'view-refresh' or the label '_Refresh'.
gtk-remove has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'list-remove' or the label '_Remove'.
gtk-revert-to-saved has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'document-revert' or the label '_Revert'.
gtk-save has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'document-save' or the label '_Save'.
gtk-save-as has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'document-save-as' or the label 'Save -As'.
gtk-select-all has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'edit-select-all' or the label 'Select -All'.
gtk-select-color has been deprecated since version 3.10 and should not be used in newly-written code.
gtk-select-font has been deprecated since version 3.10 and should not be used in newly-written code.
gtk-sort-ascending has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'view-sort-ascending'.
gtk-sort-descending has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'view-sort-descending'.
gtk-spell-check has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'tools-check-spelling'.
gtk-stop has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'process-stop' or the label '_Stop'.
gtk-strikethrough has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'format-text-strikethrough' or the label '_Strikethrough'.
gtk-undelete has been deprecated since version 3.10 and should not be used in newly-written code.
gtk-underline has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'format-text-underline' or the label '_Underline'.
gtk-undo has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'edit-undo' or the label '_Undo'.
gtk-unindent has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'format-indent-less'.
gtk-yes has been deprecated since version 3.10 and should not be used in newly-written code.
gtk-zoom-100 has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'zoom-original' or the label '_Normal Size'.
gtk-zoom-fit has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'zoom-fit-best' or the label 'Best _Fit'.
gtk-zoom-in has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'zoom-in' or the label 'Zoom _In'.
gtk-zoom-out has been deprecated since version 3.10 and should not be used in newly-written code. Use named icon 'zoom-out' or the label 'Zoom _Out'.
EOF
)
EOW

